
# -*- coding: utf-8 -*-

from sb.js.xml_dict.dict_xml import xml_to_dict
# import json

from odooClient import ODOO
c0 = ODOO('http://192.168.1.230:8069')
c0.login('cic_oa', 'admin', 'cic_admin')
# c0 = ODOO('http://192.168.1.240:8069')
# c0.login('test', 'admin', 'admin')

shenbaosheetcell = c0.env['cic_taxsb.shenbaosheet.cell']  # 单元格
shenbaosheet = c0.env['cic_taxsb.shenbaosheet']  # 表
shenbaosheetwizard = c0.env['create.shenbaosheet.wizard']  # 创建表

xml = '''<?xml version="1.0" encoding="UTF-8"?>
<jsxgs_zzs_ybnsrxxVO>
	<sbbinfo>
		<sbzlbh>10101</sbzlbh> <!-- 增值税一般纳税人申报表 申报种类编号 -->
		<ssqq>2019-02-01</ssqq><!-- 所属期起 -->
		<ssqz>2019-02-28</ssqz><!-- 所属期止 -->
		<nsrsbh>91110108MA01ATW72J</nsrsbh><!-- 申报的纳税人识别号 -->
		<area>32</area><!-- 区域 -->
		<nsqxdm>1</nsqxdm><!--纳税期限代码  1:月 2:季 3:半年 4:年 5:次-->
	</sbbinfo>
	<!-- 新国税增值税一般纳税人申报表 主表 -->
	<jsxgs_zzs_ybnsr_sbb>
		<!--(一)按适用税率计税销售额-->
		<sbbGridlbVO>
			<ewbhxh>1</ewbhxh>
			<!--(一)按适用税率计税销售额##即征即退项目##本月数-->
			<yasysljsxsejzjtxmbys/>
			<!--(一)按适用税率计税销售额##即征即退项目##本年累计-->
			<yasysljsxsejzjtxmbnlj/>
			<!--(一)按适用税率计税销售额##一般项目##本月数-->
			<yasysljsxseybxmbys/>
			<!--(一)按适用税率计税销售额##一般项目##本年累计-->
			<yasysljsxseybxmbnlj/>
		</sbbGridlbVO>
		<!--其中：应税货物销售额-->
		<sbbGridlbVO>
			<ewbhxh>2</ewbhxh>
			<!--其中：应税货物销售额##即征即退项目##本月数-->
			<qzyshwxsejzjtxmbys/>
			<!--其中：应税货物销售额##一般项目##本月数-->
			<qzyshwxseybxmbys/>
			<!--其中：应税货物销售额##即征即退项目##本年累计-->
			<qzyshwxsejzjtxmbnlj/>
		</sbbGridlbVO>
		<!--应税劳务销售额-->
		<sbbGridlbVO>
			<ewbhxh>3</ewbhxh>
			<!--应税劳务销售额##一般项目##本月数-->
			<yslwxseybxmbys/>
			<!--应税劳务销售额##即征即退项目##本月数-->
			<yslwxsejzjtxmbys/>
			<!--应税劳务销售额##即征即退项目##本年累计-->
			<yslwxsejzjtxmbnlj/>
		</sbbGridlbVO>
		<!--纳税检查调整的销售额-->
		<sbbGridlbVO>
			<ewbhxh>4</ewbhxh>
			<!--纳税检查调整的销售额##即征即退项目##本年累计-->
			<nsjcdzdxsejzjtxmbnlj/>
			<!--纳税检查调整的销售额##即征即退项目##本月数-->
			<nsjcdzdxsejzjtxmbys/>
			<!--纳税检查调整的销售额##一般项目##本月数-->
			<nsjcdzdxseybxmbys/>
		</sbbGridlbVO>
		<!--(二)按简易办法计税销售额-->
		<sbbGridlbVO>
			<ewbhxh>5</ewbhxh>
			<!--(二)按简易办法计税销售额##即征即退项目##本月数-->
			<eajybfjsxsejzjtxmbys/>
			<!--(二)按简易办法计税销售额##一般项目##本月数-->
			<eajybfjsxseybxmbys/>
			<!--(二)按简易办法计税销售额##即征即退项目##本年累计-->
			<eajybfjsxsejzjtxmbnlj/>
			<!--(二)按简易办法计税销售额##一般项目##本年累计-->
			<eajybfjsxseybxmbnlj/>
		</sbbGridlbVO>
		<!--其中：纳税检查调整的销售额-->
		<sbbGridlbVO>
			<ewbhxh>6</ewbhxh>
			<!--其中：纳税检查调整的销售额##即征即退项目##本月数-->
			<qznsjcdzdxsejzjtxmbys/>
			<!--其中：纳税检查调整的销售额##一般项目##本年累计-->
			<qznsjcdzdxseybxmbnlj/>
			<!--其中：纳税检查调整的销售额##即征即退项目##本年累计-->
			<qznsjcdzdxsejzjtxmbnlj/>
			<!--其中：纳税检查调整的销售额##一般项目##本月数-->
			<qznsjcdzdxseybxmbys/>
		</sbbGridlbVO>
		<!--(三)免、抵、退办法出口销售额-->
		<sbbGridlbVO>
			<ewbhxh>7</ewbhxh>
			<!--(三)免、抵、退办法出口销售额##一般项目##本月数-->
			<smdtbfckxseybxmbys/>
			<!--(三)免、抵、退办法出口销售额##一般项目##本年累计-->
			<smdtbfckxseybxmbnlj/>
		</sbbGridlbVO>
		<!--(四)免税销售额-->
		<sbbGridlbVO>
			<ewbhxh>8</ewbhxh>
			<!--(四)免税销售额##一般项目##本年累计-->
			<smsxseybxmbnlj/>
			<!--(四)免税销售额##一般项目##本月数-->
			<smsxseybxmbys/>
		</sbbGridlbVO>
		<!--其中：免税货物销售额-->
		<sbbGridlbVO>
			<ewbhxh>9</ewbhxh>
			<!--其中：免税货物销售额##一般项目##本年累计-->
			<qzmshwxseybxmbnlj/>
			<!--其中：免税货物销售额##一般项目##本月数-->
			<qzmshwxseybxmbys/>
		</sbbGridlbVO>
		<!--免税劳务销售额-->
		<sbbGridlbVO>
			<ewbhxh>10</ewbhxh>
			<!--免税劳务销售额##一般项目##本月数-->
			<mslwxseybxmbys/>
			<!--免税劳务销售额##一般项目##本年累计-->
			<mslwxseybxmbnlj/>
		</sbbGridlbVO>
		<!--销项税额-->
		<sbbGridlbVO>
			<ewbhxh>11</ewbhxh>
			<!--销项税额##即征即退项目##本月数-->
			<xxsejzjtxmbys/>
			<!--销项税额##一般项目##本月数-->
			<xxseybxmbys/>
			<!--销项税额##一般项目##本年累计-->
			<xxseybxmbnlj/>
			<!--销项税额##即征即退项目##本年累计-->
			<xxsejzjtxmbnlj/>
		</sbbGridlbVO>
		<!--进项税额-->
		<sbbGridlbVO>
			<ewbhxh>12</ewbhxh>
			<!--进项税额##一般项目##本月数-->
			<jxseybxmbys/>
			<!--进项税额##一般项目##本年累计-->
			<jxseybxmbnlj/>
			<!--进项税额##即征即退项目##本年累计-->
			<jxsejzjtxmbnlj/>
			<!--进项税额##即征即退项目##本月数-->
			<jxsejzjtxmbys/>
		</sbbGridlbVO>
		<!--上期留抵税额-->
		<sbbGridlbVO>
			<ewbhxh>13</ewbhxh>
			<!--上期留抵税额##一般项目##本月数-->
			<sqldseybxmbys/>
			<!--上期留抵税额##即征即退项目##本月数-->
			<sqldsejzjtxmbys/>
			<!--上期留抵税额##一般项目##本年累计-->
			<sqldseybxmbnlj/>
		</sbbGridlbVO>
		<!--进项税额转出-->
		<sbbGridlbVO>
			<ewbhxh>14</ewbhxh>
			<!--进项税额转出##一般项目##本年累计-->
			<jxsezcybxmbnlj/>
			<!--进项税额转出##即征即退项目##本月数-->
			<jxsezcjzjtxmbys/>
			<!--进项税额转出##一般项目##本月数-->
			<jxsezcybxmbys/>
		</sbbGridlbVO>
		<!--免、抵、退应退税额-->
		<sbbGridlbVO>
			<ewbhxh>15</ewbhxh>
			<!--免、抵、退应退税额##一般项目##本月数-->
			<mdtytseybxmbys/>
			<!--免、抵、退应退税额##一般项目##本年累计-->
			<mdtytseybxmbnlj/>
		</sbbGridlbVO>
		<!--按适用税率计算的纳税检查应补缴税额-->
		<sbbGridlbVO>
			<ewbhxh>16</ewbhxh>
			<!--按适用税率计算的纳税检查应补缴税额##一般项目##本月数-->
			<asysljsdnsjcybjseybxmbys/>
			<!--按适用税率计算的纳税检查应补缴税额##一般项目##本年累计-->
			<asysljsdnsjcybjseybxmbnlj/>
		</sbbGridlbVO>
		<!--应抵扣税额合计-->
		<sbbGridlbVO>
			<ewbhxh>17</ewbhxh>
			<!--应抵扣税额合计##一般项目##本月数-->
			<ydksehjybxmbys/>
			<!--应抵扣税额合计##即征即退项目##本月数-->
			<ydksehjjzjtxmbys/>
		</sbbGridlbVO>
		<!--实际抵扣税额-->
		<sbbGridlbVO>
			<ewbhxh>18</ewbhxh>
			<!--实际抵扣税额##一般项目##本月数-->
			<sjdkseybxmbys/>
			<!--实际抵扣税额##一般项目##本年累计-->
			<sjdkseybxmbnlj/>
			<!--实际抵扣税额##即征即退项目##本月数-->
			<sjdksejzjtxmbys/>
			<!--实际抵扣税额##即征即退项目##本年累计-->
			<sjdksejzjtxmbnlj/>
		</sbbGridlbVO>
		<!--应纳税额-->
		<sbbGridlbVO>
			<ewbhxh>19</ewbhxh>
			<!--应纳税额##一般项目##本月数-->
			<ynseybxmbys/>
			<!--应纳税额##一般项目##本年累计-->
			<ynseybxmbnlj/>
			<!--应纳税额##即征即退项目##本月数-->
			<ynsejzjtxmbys/>
			<!--应纳税额##即征即退项目##本年累计-->
			<ynsejzjtxmbnlj/>
		</sbbGridlbVO>
		<!--期末留抵税额-->
		<sbbGridlbVO>
			<ewbhxh>20</ewbhxh>
			<!--期末留抵税额##即征即退项目##本月数-->
			<qmldsejzjtxmbys/>
			<!--期末留抵税额##一般项目##本年累计-->
			<qmldseybxmbnlj/>
			<!--期末留抵税额##一般项目##本月数-->
			<qmldseybxmbys/>
		</sbbGridlbVO>
		<!--简易计税办法计算的应纳税额-->
		<sbbGridlbVO>
			<ewbhxh>21</ewbhxh>
			<!--简易计税办法计算的应纳税额##即征即退项目##本月数-->
			<jyjsbfjsdynsejzjtxmbys/>
			<!--简易计税办法计算的应纳税额##一般项目##本月数-->
			<jyjsbfjsdynseybxmbys/>
			<!--简易计税办法计算的应纳税额##即征即退项目##本年累计-->
			<jyjsbfjsdynsejzjtxmbnlj/>
			<!--简易计税办法计算的应纳税额##一般项目##本年累计-->
			<jyjsbfjsdynseybxmbnlj/>
		</sbbGridlbVO>
		<!--按简易计税办法计算的纳税检查应补缴税额-->
		<sbbGridlbVO>
			<ewbhxh>22</ewbhxh>
			<!--按简易计税办法计算的纳税检查应补缴税额##一般项目##本年累计-->
			<ajyjsbfjsdnsjcybjseybxmbnlj/>
			<!--按简易计税办法计算的纳税检查应补缴税额##一般项目##本月数-->
			<ajyjsbfjsdnsjcybjseybxmbys/>
		</sbbGridlbVO>
		<!--应纳税额减征额-->
		<sbbGridlbVO>
			<ewbhxh>23</ewbhxh>
			<!--应纳税额减征额##一般项目##本年累计-->
			<ynsejzeybxmbnlj/>
			<!--应纳税额减征额##即征即退项目##本年累计-->
			<ynsejzejzjtxmbnlj/>
			<!--应纳税额减征额##一般项目##本月数-->
			<ynsejzeybxmbys/>
			<!--应纳税额减征额##即征即退项目##本月数-->
			<ynsejzejzjtxmbys/>
		</sbbGridlbVO>
		<!--应纳税额合计-->
		<sbbGridlbVO>
			<ewbhxh>24</ewbhxh>
			<!--应纳税额合计##一般项目##本年累计-->
			<ynsehjybxmbnlj/>
			<!--应纳税额合计##即征即退项目##本年累计-->
			<ynsehjjzjtxmbnlj/>
			<!--应纳税额合计##一般项目##本月数-->
			<ynsehjybxmbys/>
			<!--应纳税额合计##即征即退项目##本月数-->
			<ynsehjjzjtxmbys/>
		</sbbGridlbVO>
		<!--期初未缴税额(多缴为负数)-->
		<sbbGridlbVO>
			<ewbhxh>25</ewbhxh>
			<!--期初未缴税额(多缴为负数)##即征即退项目##本月数-->
			<qcwjsedjwfsjzjtxmbys/>
		</sbbGridlbVO>
		<!--本期已缴税额-->
		<sbbGridlbVO>
			<ewbhxh>26</ewbhxh>
			<!--本期已缴税额##即征即退项目##本月数-->
			<bqyjsejzjtxmbys/>
		</sbbGridlbVO>
		<!--分次预缴税额-->
		<sbbGridlbVO>
			<ewbhxh>27</ewbhxh>
			<!--分次预缴税额##即征即退项目##本月数-->
			<fcyjsejzjtxmbys/>
			<!--分次预缴税额##一般项目##本月数-->
			<fcyjseybxmbys/>
		</sbbGridlbVO>
		<!--本期缴纳上期应纳税额-->
		<sbbGridlbVO>
			<ewbhxh>28</ewbhxh>
			<!--本期缴纳上期应纳税额##一般项目##本月数-->
			<bqjnsqynseybxmbys/>
			<!--本期缴纳上期应纳税额##即征即退项目##本月数-->
			<bqjnsqynsejzjtxmbys/>
			<!--本期缴纳上期应纳税额##即征即退项目##本年累计-->
			<bqjnsqynsejzjtxmbnlj/>
		</sbbGridlbVO>
		<!--本期缴纳欠缴税额-->
		<sbbGridlbVO>
			<ewbhxh>29</ewbhxh>
			<!--本期缴纳欠缴税额##一般项目##本月数-->
			<bqjnqjseybxmbys/>
			<!--本期缴纳欠缴税额##即征即退项目##本月数-->
			<bqjnqjsejzjtxmbys/>
			<!--本期缴纳欠缴税额##即征即退项目##本年累计-->
			<bqjnqjsejzjtxmbnlj/>
		</sbbGridlbVO>
		<!--期末未缴税额(多缴为负数)-->
		<sbbGridlbVO>
			<ewbhxh>30</ewbhxh>
			<!--期末未缴税额(多缴为负数)##即征即退项目##本月数-->
			<qmwjsedjwfsjzjtxmbys/>
			<!--期末未缴税额(多缴为负数)##即征即退项目##本年累计-->
			<qmwjsedjwfsjzjtxmbnlj/>
		</sbbGridlbVO>
		<!--其中：欠缴税额(0)-->
		<sbbGridlbVO>
			<ewbhxh>31</ewbhxh>
			<!--其中：欠缴税额(0)##即征即退项目##本月数-->
			<qzqjse0jzjtxmbys/>
		</sbbGridlbVO>
		<!--本期应补(退)税额-->
		<sbbGridlbVO>
			<ewbhxh>32</ewbhxh>
			<!--本期应补(退)税额##一般项目##本月数-->
			<bqybtseybxmbys/>
			<!--本期应补(退)税额##即征即退项目##本月数-->
			<bqybtsejzjtxmbys/>
		</sbbGridlbVO>
		<!--即征即退实际退税额-->
		<sbbGridlbVO>
			<ewbhxh>33</ewbhxh>
			<!--即征即退实际退税额##即征即退项目##本年累计-->
			<jzjtsjtsejzjtxmbnlj/>
			<!--即征即退实际退税额##即征即退项目##本月数-->
			<jzjtsjtsejzjtxmbys/>
		</sbbGridlbVO>
		<!--本期入库查补税额-->
		<sbbGridlbVO>
			<ewbhxh>34</ewbhxh>
			<!--本期入库查补税额##一般项目##本年累计-->
			<bqrkcbseybxmbnlj/>
			<!--本期入库查补税额##一般项目##本月数-->
			<bqrkcbseybxmbys/>
		</sbbGridlbVO>
		<!--期末未缴查补税额  ##新增 江苏不需要传##-->
		<sbbGridlbVO>
			<ewbhxh>35</ewbhxh>
			<!--期末未缴查补税额##一般项目##本月数-->
			<qmwjcbse/>
		</sbbGridlbVO>
		<!--期末未缴税额（多缴为负数） ##新增 江苏不需要传##-->
		<sbbGridlbVO>
			<ewbhxh>36</ewbhxh>
			<!--期末未缴税额（多缴为负数）##一般项目##本月数-->
			<qmwjse/>
		</sbbGridlbVO>
		<!--其中：欠缴税额 ##新增 江苏不需要传##-->
		<sbbGridlbVO>
			<ewbhxh>37</ewbhxh>
			<!--其中：欠缴税额 ##一般项目##本月数-->
			<qmwjseQjse/>
		</sbbGridlbVO>
		<!--出口开具专用缴款书预缴税额 ##新增 江苏不需要传##-->
		<sbbGridlbVO>
			<ewbhxh>38</ewbhxh>
			<!--出口开具专用缴款书预缴税额 ##一般项目##本月数-->
			<ckkjzyjksyjse/>
		</sbbGridlbVO>
		<!--本期已缴税额 ##新增 江苏不需要传##-->
		<sbbGridlbVO>
			<ewbhxh>39</ewbhxh>
			<!--本期已缴税额 ##一般项目##本月数-->
			<bqyjse/>
		</sbbGridlbVO>
		<!--期初未缴查补税额 ##新增 江苏不需要传##-->
		<sbbGridlbVO>
			<ewbhxh>40</ewbhxh>
			<!--期初未缴查补税额 ##一般项目##本月数-->
			<qcwjcbse/>
		</sbbGridlbVO>
		<!--期初未缴税额（多缴为负数） ##新增 江苏不需要传##-->
		<sbbGridlbVO>
			<ewbhxh>41</ewbhxh>
			<!--期初未缴税额（多缴为负数） ##一般项目##本月数-->
			<qcwjse/>
		</sbbGridlbVO>
		<!--实收出口开具专用缴款书退税额 ##新增 江苏不需要传##-->
		<sbbGridlbVO>
			<ewbhxh>42</ewbhxh>
			<!--实收出口开具专用缴款书退税额 ##一般项目##本月数-->
			<ssckkjzyjkstse/>
		</sbbGridlbVO>		
	</jsxgs_zzs_ybnsr_sbb>
	<!-- 新国税增值税一般纳税人申报表 附表一 -->
	<jsxgs_zzs_ybnsr_fb1>
		<!--一、一般计税方法计税##全部征税项目##13%税率的货物及加工修理修配劳务-->
		<fb1GridlbVO>
			<ewbhxh>1</ewbhxh>
			<!--一、一般计税方法计税##全部征税项目##13%税率的货物及加工修理修配劳务##合计##销项(应纳)税额-->
			<yybjsffjsqbzsxm13sldhwjjgxlxplwhjxxynse/>
			<!--一、一般计税方法计税##全部征税项目##13%税率的货物及加工修理修配劳务##开具其他发票##销售额-->
			<yybjsffjsqbzsxm13sldhwjjgxlxplwkjqtfpxse/>
			<!--一、一般计税方法计税##全部征税项目##13%税率的货物及加工修理修配劳务##未开具发票##销售额-->
			<yybjsffjsqbzsxm13sldhwjjgxlxplwwkjfpxse/>
			<!--一、一般计税方法计税##全部征税项目##13%税率的货物及加工修理修配劳务##纳税检查调整##销售额-->
			<yybjsffjsqbzsxm13sldhwjjgxlxplwnsjcdzxse/>
			<!--一、一般计税方法计税##全部征税项目##13%税率的货物及加工修理修配劳务##开具税控增值税专用发票##销项(应纳)税额-->
			<yybjsffjsqbzsxm13sldhwjjgxlxplwkjskzzszyfpxxynse/>
			<!--一、一般计税方法计税##全部征税项目##13%税率的货物及加工修理修配劳务##开具税控增值税专用发票##销售额-->
			<yybjsffjsqbzsxm13sldhwjjgxlxplwkjskzzszyfpxse/>
			<!--一、一般计税方法计税##全部征税项目##13%税率的货物及加工修理修配劳务##开具其他发票##销项(应纳)税额-->
			<yybjsffjsqbzsxm13sldhwjjgxlxplwkjqtfpxxynse/>
			<!--一、一般计税方法计税##全部征税项目##13%税率的货物及加工修理修配劳务##纳税检查调整##销项(应纳)税额-->
			<yybjsffjsqbzsxm13sldhwjjgxlxplwnsjcdzxxynse/>
			<!--一、一般计税方法计税##全部征税项目##13%税率的货物及加工修理修配劳务##合计##销售额-->
			<yybjsffjsqbzsxm13sldhwjjgxlxplwhjxse/>
			<!--一、一般计税方法计税##全部征税项目##13%税率的货物及加工修理修配劳务##未开具发票##销项(应纳)税额-->
			<yybjsffjsqbzsxm13sldhwjjgxlxplwwkjfpxxynse/>
		</fb1GridlbVO>
		<!--一、一般计税方法计税##全部征税项目##13%税率的服务、不动产和无形资产-->
		<fb1GridlbVO>
			<ewbhxh>2</ewbhxh>
			<!--一、一般计税方法计税##全部征税项目##13%税率的服务、不动产和无形资产##合计##销售额-->
			<yybjsffjsqbzsxm13sldfwbdchwxzchjxse/>
			<!--一、一般计税方法计税##全部征税项目##13%税率的服务、不动产和无形资产##未开具发票##销项(应纳)税额-->
			<yybjsffjsqbzsxm13sldfwbdchwxzcwkjfpxxynse/>
			<!--一、一般计税方法计税##全部征税项目##13%税率的服务、不动产和无形资产##合计##销项(应纳)税额-->
			<yybjsffjsqbzsxm13sldfwbdchwxzchjxxynse/>
			<!--一、一般计税方法计税##全部征税项目##13%税率的服务、不动产和无形资产##应税服务扣除项目本期实际扣除金额##价税合计-->
			<yybjsffjsqbzsxm13sldfwbdchwxzcysfwkcxmbqsjkcjejshj/>
			<!--一、一般计税方法计税##全部征税项目##13%税率的服务、不动产和无形资产##扣除后##含税(免税)销售额-->
			<yybjsffjsqbzsxm13sldfwbdchwxzckchhsmsxse/>
			<!--一、一般计税方法计税##全部征税项目##13%税率的服务、不动产和无形资产##开具税控增值税专用发票##销项(应纳)税额-->
			<yybjsffjsqbzsxm13sldfwbdchwxzckjskzzszyfpxxynse/>
			<!--一、一般计税方法计税##全部征税项目##13%税率的服务、不动产和无形资产##开具税控增值税专用发票##销售额-->
			<yybjsffjsqbzsxm13sldfwbdchwxzckjskzzszyfpxse/>
			<!--一、一般计税方法计税##全部征税项目##13%税率的服务、不动产和无形资产##未开具发票##销售额-->
			<yybjsffjsqbzsxm13sldfwbdchwxzcwkjfpxse/>
			<!--一、一般计税方法计税##全部征税项目##13%税率的服务、不动产和无形资产##合计##价税合计-->
			<yybjsffjsqbzsxm13sldfwbdchwxzchjjshj/>
			<!--一、一般计税方法计税##全部征税项目##13%税率的服务、不动产和无形资产##纳税检查调整##销项(应纳)税额-->
			<yybjsffjsqbzsxm13sldfwbdchwxzcnsjcdzxxynse/>
			<!--一、一般计税方法计税##全部征税项目##13%税率的服务、不动产和无形资产##扣除后##销项(应纳)税额-->
			<yybjsffjsqbzsxm13sldfwbdchwxzckchxxynse/>
			<!--一、一般计税方法计税##全部征税项目##13%税率的服务、不动产和无形资产##开具其他发票##销售额-->
			<yybjsffjsqbzsxm13sldfwbdchwxzckjqtfpxse/>
			<!--一、一般计税方法计税##全部征税项目##13%税率的服务、不动产和无形资产##纳税检查调整##销售额-->
			<yybjsffjsqbzsxm13sldfwbdchwxzcnsjcdzxse/>
			<!--一、一般计税方法计税##全部征税项目##13%税率的服务、不动产和无形资产##开具其他发票##销项(应纳)税额-->
			<yybjsffjsqbzsxm13sldfwbdchwxzckjqtfpxxynse/>
		</fb1GridlbVO>
		<!--一、一般计税方法计税##全部征税项目##9%税率的货物及加工修理修配劳务-->
		<fb1GridlbVO>
			<ewbhxh>3</ewbhxh>
			<!--一、一般计税方法计税##全部征税项目##9%税率的货物及加工修理修配劳务##开具税控增值税专用发票##销售额-->
			<yybjsffjsqbzsxm9sldhwjjgxlxplwkjskzzszyfpxse/>
			<!--一、一般计税方法计税##全部征税项目##9%税率的货物及加工修理修配劳务##纳税检查调整##销售额-->
			<yybjsffjsqbzsxm9sldhwjjgxlxplwnsjcdzxse/>
			<!--一、一般计税方法计税##全部征税项目##9%税率的货物及加工修理修配劳务##合计##销项(应纳)税额-->
			<yybjsffjsqbzsxm9sldhwjjgxlxplwhjxxynse/>
			<!--一、一般计税方法计税##全部征税项目##9%税率的货物及加工修理修配劳务##纳税检查调整##销项(应纳)税额-->
			<yybjsffjsqbzsxm9sldhwjjgxlxplwnsjcdzxxynse/>
			<!--一、一般计税方法计税##全部征税项目##9%税率的货物及加工修理修配劳务##开具税控增值税专用发票##销项(应纳)税额-->
			<yybjsffjsqbzsxm9sldhwjjgxlxplwkjskzzszyfpxxynse/>
			<!--一、一般计税方法计税##全部征税项目##9%税率的货物及加工修理修配劳务##开具其他发票##销项(应纳)税额-->
			<yybjsffjsqbzsxm9sldhwjjgxlxplwkjqtfpxxynse/>
			<!--一、一般计税方法计税##全部征税项目##9%税率的货物及加工修理修配劳务##未开具发票##销项(应纳)税额-->
			<yybjsffjsqbzsxm9sldhwjjgxlxplwwkjfpxxynse/>
			<!--一、一般计税方法计税##全部征税项目##9%税率的货物及加工修理修配劳务##合计##销售额-->
			<yybjsffjsqbzsxm9sldhwjjgxlxplwhjxse/>
			<!--一、一般计税方法计税##全部征税项目##9%税率的货物及加工修理修配劳务##开具其他发票##销售额-->
			<yybjsffjsqbzsxm9sldhwjjgxlxplwkjqtfpxse/>
			<!--一、一般计税方法计税##全部征税项目##9%税率的货物及加工修理修配劳务##未开具发票##销售额-->
			<yybjsffjsqbzsxm9sldhwjjgxlxplwwkjfpxse/>
		</fb1GridlbVO>
		<!--一、一般计税方法计税##全部征税项目##9%税率的服务、不动产和无形资产-->
		<fb1GridlbVO>
			<ewbhxh>4</ewbhxh>
			<!--一、一般计税方法计税##全部征税项目##9%税率的服务、不动产和无形资产##开具税控增值税专用发票##销项(应纳)税额-->
			<yybjsffjsqbzsxm9sldfwbdchwxzckjskzzszyfpxxynse/>
			<!--一、一般计税方法计税##全部征税项目##9%税率的服务、不动产和无形资产##未开具发票##销项(应纳)税额-->
			<yybjsffjsqbzsxm9sldfwbdchwxzcwkjfpxxynse/>
			<!--一、一般计税方法计税##全部征税项目##9%税率的服务、不动产和无形资产##纳税检查调整##销项(应纳)税额-->
			<yybjsffjsqbzsxm9sldfwbdchwxzcnsjcdzxxynse/>
			<!--一、一般计税方法计税##全部征税项目##9%税率的服务、不动产和无形资产##扣除后##销项(应纳)税额-->
			<yybjsffjsqbzsxm9sldfwbdchwxzckchxxynse/>
			<!--一、一般计税方法计税##全部征税项目##9%税率的服务、不动产和无形资产##合计##销售额-->
			<yybjsffjsqbzsxm9sldfwbdchwxzchjxse/>
			<!--一、一般计税方法计税##全部征税项目##9%税率的服务、不动产和无形资产##扣除后##含税(免税)销售额-->
			<yybjsffjsqbzsxm9sldfwbdchwxzckchhsmsxse/>
			<!--一、一般计税方法计税##全部征税项目##9%税率的服务、不动产和无形资产##合计##销项(应纳)税额-->
			<yybjsffjsqbzsxm9sldfwbdchwxzchjxxynse/>
			<!--一、一般计税方法计税##全部征税项目##9%税率的服务、不动产和无形资产##开具税控增值税专用发票##销售额-->
			<yybjsffjsqbzsxm9sldfwbdchwxzckjskzzszyfpxse/>
			<!--一、一般计税方法计税##全部征税项目##9%税率的服务、不动产和无形资产##开具其他发票##销售额-->
			<yybjsffjsqbzsxm9sldfwbdchwxzckjqtfpxse/>
			<!--一、一般计税方法计税##全部征税项目##9%税率的服务、不动产和无形资产##开具其他发票##销项(应纳)税额-->
			<yybjsffjsqbzsxm9sldfwbdchwxzckjqtfpxxynse/>
			<!--一、一般计税方法计税##全部征税项目##9%税率的服务、不动产和无形资产##未开具发票##销售额-->
			<yybjsffjsqbzsxm9sldfwbdchwxzcwkjfpxse/>
			<!--一、一般计税方法计税##全部征税项目##9%税率的服务、不动产和无形资产##合计##价税合计-->
			<yybjsffjsqbzsxm9sldfwbdchwxzchjjshj/>
			<!--一、一般计税方法计税##全部征税项目##9%税率的服务、不动产和无形资产##纳税检查调整##销售额-->
			<yybjsffjsqbzsxm9sldfwbdchwxzcnsjcdzxse/>
			<!--一、一般计税方法计税##全部征税项目##9%税率的服务、不动产和无形资产##应税服务扣除项目本期实际扣除金额##价税合计-->
			<yybjsffjsqbzsxm9sldfwbdchwxzcysfwkcxmbqsjkcjejshj/>
		</fb1GridlbVO>
		<!--一、一般计税方法计税##全部征税项目##6%税率-->
		<fb1GridlbVO>
			<ewbhxh>5</ewbhxh>
			<!--一、一般计税方法计税##全部征税项目##6%税率##开具其他发票##销售额-->
			<yybjsffjsqbzsxm6slkjqtfpxse/>
			<!--一、一般计税方法计税##全部征税项目##6%税率##纳税检查调整##销售额-->
			<yybjsffjsqbzsxm6slnsjcdzxse/>
			<!--一、一般计税方法计税##全部征税项目##6%税率##扣除后##销项(应纳)税额-->
			<yybjsffjsqbzsxm6slkchxxynse/>
			<!--一、一般计税方法计税##全部征税项目##6%税率##纳税检查调整##销项(应纳)税额-->
			<yybjsffjsqbzsxm6slnsjcdzxxynse/>
			<!--一、一般计税方法计税##全部征税项目##6%税率##开具其他发票##销项(应纳)税额-->
			<yybjsffjsqbzsxm6slkjqtfpxxynse/>
			<!--一、一般计税方法计税##全部征税项目##6%税率##未开具发票##销项(应纳)税额-->
			<yybjsffjsqbzsxm6slwkjfpxxynse/>
			<!--一、一般计税方法计税##全部征税项目##6%税率##合计##销项(应纳)税额-->
			<yybjsffjsqbzsxm6slhjxxynse/>
			<!--一、一般计税方法计税##全部征税项目##6%税率##开具税控增值税专用发票##销项(应纳)税额-->
			<yybjsffjsqbzsxm6slkjskzzszyfpxxynse/>
			<!--一、一般计税方法计税##全部征税项目##6%税率##开具税控增值税专用发票##销售额-->
			<yybjsffjsqbzsxm6slkjskzzszyfpxse/>
			<!--一、一般计税方法计税##全部征税项目##6%税率##合计##价税合计-->
			<yybjsffjsqbzsxm6slhjjshj/>
			<!--一、一般计税方法计税##全部征税项目##6%税率##应税服务扣除项目本期实际扣除金额##价税合计-->
			<yybjsffjsqbzsxm6slysfwkcxmbqsjkcjejshj/>
			<!--一、一般计税方法计税##全部征税项目##6%税率##合计##销售额-->
			<yybjsffjsqbzsxm6slhjxse/>
			<!--一、一般计税方法计税##全部征税项目##6%税率##未开具发票##销售额-->
			<yybjsffjsqbzsxm6slwkjfpxse/>
			<!--一、一般计税方法计税##全部征税项目##6%税率##扣除后##含税(免税)销售额-->
			<yybjsffjsqbzsxm6slkchhsmsxse/>
		</fb1GridlbVO>
		<!--一、一般计税方法计税##其中：即征即退项目##即征即退货物及加工修理修配劳务-->
		<fb1GridlbVO>
			<ewbhxh>6</ewbhxh>
			<!--一、一般计税方法计税##其中：即征即退项目##即征即退货物及加工修理修配劳务##合计##销售额-->
			<yybjsffjsqzjzjtxmjzjthwjjgxlxplwhjxse/>
			<!--一、一般计税方法计税##其中：即征即退项目##即征即退货物及加工修理修配劳务##合计##销项(应纳)税额-->
			<yybjsffjsqzjzjtxmjzjthwjjgxlxplwhjxxynse/>
		</fb1GridlbVO>
		<!--一、一般计税方法计税##其中：即征即退项目##即征即退服务、不动产和无形资产-->
		<fb1GridlbVO>
			<ewbhxh>7</ewbhxh>
			<!--一、一般计税方法计税##其中：即征即退项目##即征即退服务、不动产和无形资产##合计##销售额-->
			<yybjsffjsqzjzjtxmjzjtfwbdchwxzchjxse/>
			<!--一、一般计税方法计税##其中：即征即退项目##即征即退服务、不动产和无形资产##合计##销项(应纳)税额-->
			<yybjsffjsqzjzjtxmjzjtfwbdchwxzchjxxynse/>
			<!--一、一般计税方法计税##其中：即征即退项目##即征即退服务、不动产和无形资产##扣除后##含税(免税)销售额-->
			<yybjsffjsqzjzjtxmjzjtfwbdchwxzckchhsmsxse/>
			<!--一、一般计税方法计税##其中：即征即退项目##即征即退服务、不动产和无形资产##应税服务扣除项目本期实际扣除金额##价税合计-->
			<yybjsffjsqzjzjtxmjzjtfwbdchwxzcysfwkcxmbqsjkcjejshj/>
			<!--一、一般计税方法计税##其中：即征即退项目##即征即退服务、不动产和无形资产##扣除后##销项(应纳)税额-->
			<yybjsffjsqzjzjtxmjzjtfwbdchwxzckchxxynse/>
			<!--一、一般计税方法计税##其中：即征即退项目##即征即退服务、不动产和无形资产##合计##价税合计-->
			<yybjsffjsqzjzjtxmjzjtfwbdchwxzchjjshj/>
		</fb1GridlbVO>
		<!--二、简易计税方法计税##全部征税项目##6%征收率-->
		<fb1GridlbVO>
			<ewbhxh>8</ewbhxh>
			<!--二、简易计税方法计税##全部征税项目##6%征收率##开具其他发票##销售额-->
			<ejyjsffjsqbzsxm6zslkjqtfpxse/>
			<!--二、简易计税方法计税##全部征税项目##6%征收率##开具其他发票##销项(应纳)税额-->
			<ejyjsffjsqbzsxm6zslkjqtfpxxynse/>
			<!--二、简易计税方法计税##全部征税项目##6%征收率##开具税控增值税专用发票##销项(应纳)税额-->
			<ejyjsffjsqbzsxm6zslkjskzzszyfpxxynse/>
			<!--二、简易计税方法计税##全部征税项目##6%征收率##未开具发票##销项(应纳)税额-->
			<ejyjsffjsqbzsxm6zslwkjfpxxynse/>
			<!--二、简易计税方法计税##全部征税项目##6%征收率##开具税控增值税专用发票##销售额-->
			<ejyjsffjsqbzsxm6zslkjskzzszyfpxse/>
			<!--二、简易计税方法计税##全部征税项目##6%征收率##合计##销售额-->
			<ejyjsffjsqbzsxm6zslhjxse/>
			<!--二、简易计税方法计税##全部征税项目##6%征收率##合计##销项(应纳)税额-->
			<ejyjsffjsqbzsxm6zslhjxxynse/>
			<!--二、简易计税方法计税##全部征税项目##6%征收率##未开具发票##销售额-->
			<ejyjsffjsqbzsxm6zslwkjfpxse/>
		</fb1GridlbVO>
		<!--二、简易计税方法计税##全部征税项目##5%征收率的货物及加工修理修配劳务-->
		<fb1GridlbVO>
			<ewbhxh>9</ewbhxh>
			<!--二、简易计税方法计税##全部征税项目##5%征收率的货物及加工修理修配劳务##开具税控增值税专用发票##销售额-->
			<ejyjsffjsqbzsxm5zsldhwjjgxlxplwkjskzzszyfpxse/>
			<!--二、简易计税方法计税##全部征税项目##5%征收率的货物及加工修理修配劳务##合计##销项(应纳)税额-->
			<ejyjsffjsqbzsxm5zsldhwjjgxlxplwhjxxynse/>
			<!--二、简易计税方法计税##全部征税项目##5%征收率的货物及加工修理修配劳务##未开具发票##销项(应纳)税额-->
			<ejyjsffjsqbzsxm5zsldhwjjgxlxplwwkjfpxxynse/>
			<!--二、简易计税方法计税##全部征税项目##5%征收率的货物及加工修理修配劳务##未开具发票##销售额-->
			<ejyjsffjsqbzsxm5zsldhwjjgxlxplwwkjfpxse/>
			<!--二、简易计税方法计税##全部征税项目##5%征收率的货物及加工修理修配劳务##开具其他发票##销售额-->
			<ejyjsffjsqbzsxm5zsldhwjjgxlxplwkjqtfpxse/>
			<!--二、简易计税方法计税##全部征税项目##5%征收率的货物及加工修理修配劳务##开具其他发票##销项(应纳)税额-->
			<ejyjsffjsqbzsxm5zsldhwjjgxlxplwkjqtfpxxynse/>
			<!--二、简易计税方法计税##全部征税项目##5%征收率的货物及加工修理修配劳务##开具税控增值税专用发票##销项(应纳)税额-->
			<ejyjsffjsqbzsxm5zsldhwjjgxlxplwkjskzzszyfpxxynse/>
			<!--二、简易计税方法计税##全部征税项目##5%征收率的货物及加工修理修配劳务##合计##销售额-->
			<ejyjsffjsqbzsxm5zsldhwjjgxlxplwhjxse/>
		</fb1GridlbVO>
		<!--二、简易计税方法计税##全部征税项目##5%征收率的服务、不动产和无形资产-->
		<fb1GridlbVO>
			<ewbhxh>10</ewbhxh>
			<!--二、简易计税方法计税##全部征税项目##5%征收率的服务、不动产和无形资产##合计##价税合计-->
			<ejyjsffjsqbzsxm5zsldfwbdchwxzchjjshj/>
			<!--二、简易计税方法计税##全部征税项目##5%征收率的服务、不动产和无形资产##合计##销项(应纳)税额-->
			<ejyjsffjsqbzsxm5zsldfwbdchwxzchjxxynse/>
			<!--二、简易计税方法计税##全部征税项目##5%征收率的服务、不动产和无形资产##未开具发票##销项(应纳)税额-->
			<ejyjsffjsqbzsxm5zsldfwbdchwxzcwkjfpxxynse/>
			<!--二、简易计税方法计税##全部征税项目##5%征收率的服务、不动产和无形资产##未开具发票##销售额-->
			<ejyjsffjsqbzsxm5zsldfwbdchwxzcwkjfpxse/>
			<!--二、简易计税方法计税##全部征税项目##5%征收率的服务、不动产和无形资产##开具税控增值税专用发票##销售额-->
			<ejyjsffjsqbzsxm5zsldfwbdchwxzckjskzzszyfpxse/>
			<!--二、简易计税方法计税##全部征税项目##5%征收率的服务、不动产和无形资产##开具税控增值税专用发票##销项(应纳)税额-->
			<ejyjsffjsqbzsxm5zsldfwbdchwxzckjskzzszyfpxxynse/>
			<!--二、简易计税方法计税##全部征税项目##5%征收率的服务、不动产和无形资产##合计##销售额-->
			<ejyjsffjsqbzsxm5zsldfwbdchwxzchjxse/>
			<!--二、简易计税方法计税##全部征税项目##5%征收率的服务、不动产和无形资产##开具其他发票##销项(应纳)税额-->
			<ejyjsffjsqbzsxm5zsldfwbdchwxzckjqtfpxxynse/>
			<!--二、简易计税方法计税##全部征税项目##5%征收率的服务、不动产和无形资产##开具其他发票##销售额-->
			<ejyjsffjsqbzsxm5zsldfwbdchwxzckjqtfpxse/>
			<!--二、简易计税方法计税##全部征税项目##5%征收率的服务、不动产和无形资产##应税服务扣除项目本期实际扣除金额##价税合计-->
			<ejyjsffjsqbzsxm5zsldfwbdchwxzcysfwkcxmbqsjkcjejshj/>
			<!--二、简易计税方法计税##全部征税项目##5%征收率的服务、不动产和无形资产##扣除后##含税(免税)销售额-->
			<ejyjsffjsqbzsxm5zsldfwbdchwxzckchhsmsxse/>
			<!--二、简易计税方法计税##全部征税项目##5%征收率的服务、不动产和无形资产##扣除后##销项(应纳)税额-->
			<ejyjsffjsqbzsxm5zsldfwbdchwxzckchxxynse/>
		</fb1GridlbVO>
		<!--二、简易计税方法计税##全部征税项目##4%征收率-->
		<fb1GridlbVO>
			<ewbhxh>11</ewbhxh>
			<!--二、简易计税方法计税##全部征税项目##4%征收率##开具其他发票##销项(应纳)税额-->
			<ejyjsffjsqbzsxm4zslkjqtfpxxynse/>
			<!--二、简易计税方法计税##全部征税项目##4%征收率##合计##销项(应纳)税额-->
			<ejyjsffjsqbzsxm4zslhjxxynse/>
			<!--二、简易计税方法计税##全部征税项目##4%征收率##开具税控增值税专用发票##销项(应纳)税额-->
			<ejyjsffjsqbzsxm4zslkjskzzszyfpxxynse/>
			<!--二、简易计税方法计税##全部征税项目##4%征收率##开具其他发票##销售额-->
			<ejyjsffjsqbzsxm4zslkjqtfpxse/>
			<!--二、简易计税方法计税##全部征税项目##4%征收率##未开具发票##销售额-->
			<ejyjsffjsqbzsxm4zslwkjfpxse/>
			<!--二、简易计税方法计税##全部征税项目##4%征收率##合计##销售额-->
			<ejyjsffjsqbzsxm4zslhjxse/>
			<!--二、简易计税方法计税##全部征税项目##4%征收率##开具税控增值税专用发票##销售额-->
			<ejyjsffjsqbzsxm4zslkjskzzszyfpxse/>
			<!--二、简易计税方法计税##全部征税项目##4%征收率##未开具发票##销项(应纳)税额-->
			<ejyjsffjsqbzsxm4zslwkjfpxxynse/>
		</fb1GridlbVO>
		<!--二、简易计税方法计税##全部征税项目##3%征收率的货物及加工修理修配劳务-->
		<fb1GridlbVO>
			<ewbhxh>12</ewbhxh>
			<!--二、简易计税方法计税##全部征税项目##3%征收率的货物及加工修理修配劳务##开具税控增值税专用发票##销售额-->
			<ejyjsffjsqbzsxm3zsldhwjjgxlxplwkjskzzszyfpxse/>
			<!--二、简易计税方法计税##全部征税项目##3%征收率的货物及加工修理修配劳务##未开具发票##销项(应纳)税额-->
			<ejyjsffjsqbzsxm3zsldhwjjgxlxplwwkjfpxxynse/>
			<!--二、简易计税方法计税##全部征税项目##3%征收率的货物及加工修理修配劳务##合计##销售额-->
			<ejyjsffjsqbzsxm3zsldhwjjgxlxplwhjxse/>
			<!--二、简易计税方法计税##全部征税项目##3%征收率的货物及加工修理修配劳务##未开具发票##销售额-->
			<ejyjsffjsqbzsxm3zsldhwjjgxlxplwwkjfpxse/>
			<!--二、简易计税方法计税##全部征税项目##3%征收率的货物及加工修理修配劳务##开具其他发票##销项(应纳)税额-->
			<ejyjsffjsqbzsxm3zsldhwjjgxlxplwkjqtfpxxynse/>
			<!--二、简易计税方法计税##全部征税项目##3%征收率的货物及加工修理修配劳务##开具税控增值税专用发票##销项(应纳)税额-->
			<ejyjsffjsqbzsxm3zsldhwjjgxlxplwkjskzzszyfpxxynse/>
			<!--二、简易计税方法计税##全部征税项目##3%征收率的货物及加工修理修配劳务##开具其他发票##销售额-->
			<ejyjsffjsqbzsxm3zsldhwjjgxlxplwkjqtfpxse/>
			<!--二、简易计税方法计税##全部征税项目##3%征收率的货物及加工修理修配劳务##合计##销项(应纳)税额-->
			<ejyjsffjsqbzsxm3zsldhwjjgxlxplwhjxxynse/>
		</fb1GridlbVO>
		<!--二、简易计税方法计税##全部征税项目##3%征收率的服务、不动产和无形资产-->
		<fb1GridlbVO>
			<ewbhxh>13</ewbhxh>
			<!--二、简易计税方法计税##全部征税项目##3%征收率的服务、不动产和无形资产##合计##价税合计-->
			<ejyjsffjsqbzsxm3zsldfwbdchwxzchjjshj/>
			<!--二、简易计税方法计税##全部征税项目##3%征收率的服务、不动产和无形资产##扣除后##销项(应纳)税额-->
			<ejyjsffjsqbzsxm3zsldfwbdchwxzckchxxynse/>
			<!--二、简易计税方法计税##全部征税项目##3%征收率的服务、不动产和无形资产##开具税控增值税专用发票##销售额-->
			<ejyjsffjsqbzsxm3zsldfwbdchwxzckjskzzszyfpxse/>
			<!--二、简易计税方法计税##全部征税项目##3%征收率的服务、不动产和无形资产##合计##销售额-->
			<ejyjsffjsqbzsxm3zsldfwbdchwxzchjxse/>
			<!--二、简易计税方法计税##全部征税项目##3%征收率的服务、不动产和无形资产##开具其他发票##销项(应纳)税额-->
			<ejyjsffjsqbzsxm3zsldfwbdchwxzckjqtfpxxynse/>
			<!--二、简易计税方法计税##全部征税项目##3%征收率的服务、不动产和无形资产##开具其他发票##销售额-->
			<ejyjsffjsqbzsxm3zsldfwbdchwxzckjqtfpxse/>
			<!--二、简易计税方法计税##全部征税项目##3%征收率的服务、不动产和无形资产##未开具发票##销售额-->
			<ejyjsffjsqbzsxm3zsldfwbdchwxzcwkjfpxse/>
			<!--二、简易计税方法计税##全部征税项目##3%征收率的服务、不动产和无形资产##未开具发票##销项(应纳)税额-->
			<ejyjsffjsqbzsxm3zsldfwbdchwxzcwkjfpxxynse/>
			<!--二、简易计税方法计税##全部征税项目##3%征收率的服务、不动产和无形资产##开具税控增值税专用发票##销项(应纳)税额-->
			<ejyjsffjsqbzsxm3zsldfwbdchwxzckjskzzszyfpxxynse/>
			<!--二、简易计税方法计税##全部征税项目##3%征收率的服务、不动产和无形资产##扣除后##含税(免税)销售额-->
			<ejyjsffjsqbzsxm3zsldfwbdchwxzckchhsmsxse/>
			<!--二、简易计税方法计税##全部征税项目##3%征收率的服务、不动产和无形资产##应税服务扣除项目本期实际扣除金额##价税合计-->
			<ejyjsffjsqbzsxm3zsldfwbdchwxzcysfwkcxmbqsjkcjejshj/>
			<!--二、简易计税方法计税##全部征税项目##3%征收率的服务、不动产和无形资产##合计##销项(应纳)税额-->
			<ejyjsffjsqbzsxm3zsldfwbdchwxzchjxxynse/>
		</fb1GridlbVO>
		<!--二、简易计税方法计税##其中：即征即退项目##即征即退货物及加工修理修配劳务-->
		<fb1GridlbVO>
			<ewbhxh>14</ewbhxh>
			<!--二、简易计税方法计税##其中：即征即退项目##即征即退货物及加工修理修配劳务##合计##销项(应纳)税额-->
			<ejyjsffjsqzjzjtxmjzjthwjjgxlxplwhjxxynse/>
			<!--二、简易计税方法计税##其中：即征即退项目##即征即退货物及加工修理修配劳务##合计##销售额-->
			<ejyjsffjsqzjzjtxmjzjthwjjgxlxplwhjxse/>
		</fb1GridlbVO>
		<!--二、简易计税方法计税##其中：即征即退项目##即征即退服务、不动产和无形资产-->
		<fb1GridlbVO>
			<ewbhxh>15</ewbhxh>
			<!--二、简易计税方法计税##其中：即征即退项目##即征即退服务、不动产和无形资产##合计##销项(应纳)税额-->
			<ejyjsffjsqzjzjtxmjzjtfwbdchwxzchjxxynse/>
			<!--二、简易计税方法计税##其中：即征即退项目##即征即退服务、不动产和无形资产##应税服务扣除项目本期实际扣除金额##价税合计-->
			<ejyjsffjsqzjzjtxmjzjtfwbdchwxzcysfwkcxmbqsjkcjejshj/>
			<!--二、简易计税方法计税##其中：即征即退项目##即征即退服务、不动产和无形资产##扣除后##含税(免税)销售额-->
			<ejyjsffjsqzjzjtxmjzjtfwbdchwxzckchhsmsxse/>
			<!--二、简易计税方法计税##其中：即征即退项目##即征即退服务、不动产和无形资产##扣除后##销项(应纳)税额-->
			<ejyjsffjsqzjzjtxmjzjtfwbdchwxzckchxxynse/>
			<!--二、简易计税方法计税##其中：即征即退项目##即征即退服务、不动产和无形资产##合计##价税合计-->
			<ejyjsffjsqzjzjtxmjzjtfwbdchwxzchjjshj/>
			<!--二、简易计税方法计税##其中：即征即退项目##即征即退服务、不动产和无形资产##合计##销售额-->
			<ejyjsffjsqzjzjtxmjzjtfwbdchwxzchjxse/>
		</fb1GridlbVO>
		<!--三、免抵退税##货物及加工修理修配劳务-->
		<fb1GridlbVO>
			<ewbhxh>16</ewbhxh>
			<!--三、免抵退税##货物及加工修理修配劳务##开具其他发票##销售额-->
			<smdtshwjjgxlxplwkjqtfpxse/>
			<!--三、免抵退税##货物及加工修理修配劳务##合计##销售额-->
			<smdtshwjjgxlxplwhjxse/>
			<!--三、免抵退税##货物及加工修理修配劳务##未开具发票##销售额-->
			<smdtshwjjgxlxplwwkjfpxse/>
		</fb1GridlbVO>
		<!--三、免抵退税##服务、不动产和无形资产-->
		<fb1GridlbVO>
			<ewbhxh>17</ewbhxh>
			<!--三、免抵退税##服务、不动产和无形资产##未开具发票##销售额-->
			<smdtsfwbdchwxzcwkjfpxse/>
			<!--三、免抵退税##服务、不动产和无形资产##开具其他发票##销售额-->
			<smdtsfwbdchwxzckjqtfpxse/>
			<!--三、免抵退税##服务、不动产和无形资产##合计##销售额-->
			<smdtsfwbdchwxzchjxse/>
			<!--三、免抵退税##服务、不动产和无形资产##应税服务扣除项目本期实际扣除金额##价税合计-->
			<smdtsfwbdchwxzcysfwkcxmbqsjkcjejshj/>
			<!--三、免抵退税##服务、不动产和无形资产##扣除后##含税(免税)销售额-->
			<smdtsfwbdchwxzckchhsmsxse/>
			<!--三、免抵退税##服务、不动产和无形资产##合计##价税合计-->
			<smdtsfwbdchwxzchjjshj/>
		</fb1GridlbVO>
		<!--四、免税##货物及加工修理修配劳务-->
		<fb1GridlbVO>
			<ewbhxh>18</ewbhxh>
			<!--四、免税##货物及加工修理修配劳务##开具其他发票##销售额-->
			<smshwjjgxlxplwkjqtfpxse/>
			<!--四、免税##货物及加工修理修配劳务##开具税控增值税专用发票##销项(应纳)税额-->
			<smshwjjgxlxplwkjskzzszyfpxxynse/>
			<!--四、免税##货物及加工修理修配劳务##开具税控增值税专用发票##销售额-->
			<smshwjjgxlxplwkjskzzszyfpxse/>
			<!--四、免税##货物及加工修理修配劳务##未开具发票##销售额-->
			<smshwjjgxlxplwwkjfpxse/>
			<!--四、免税##货物及加工修理修配劳务##合计##销售额-->
			<smshwjjgxlxplwhjxse/>
		</fb1GridlbVO>
		<!--四、免税##服务、不动产和无形资产-->
		<fb1GridlbVO>
			<ewbhxh>19</ewbhxh>
			<!--四、免税##服务、不动产和无形资产##扣除后##含税(免税)销售额-->
			<smsfwbdchwxzckchhsmsxse/>
			<!--四、免税##服务、不动产和无形资产##合计##价税合计-->
			<smsfwbdchwxzchjjshj/>
			<!--四、免税##服务、不动产和无形资产##应税服务扣除项目本期实际扣除金额##价税合计-->
			<smsfwbdchwxzcysfwkcxmbqsjkcjejshj/>
			<!--四、免税##服务、不动产和无形资产##开具其他发票##销售额-->
			<smsfwbdchwxzckjqtfpxse/>
			<!--四、免税##服务、不动产和无形资产##合计##销售额-->
			<smsfwbdchwxzchjxse/>
			<!--四、免税##服务、不动产和无形资产##未开具发票##销售额-->
			<smsfwbdchwxzcwkjfpxse/>
		</fb1GridlbVO>
		<!--增值税专用发票##13%-->
		<fb1GridlbVO>
			<ewbhxh>20</ewbhxh>
			<!--增值税专用发票##13%##开具税控增值税专用发票##销项(应纳)税额-->
			<zzszyfp13kjskzzszyfpxxynse/>
			<!--增值税专用发票##13%##开具税控增值税专用发票##销售额-->
			<zzszyfp13kjskzzszyfpxse/>
		</fb1GridlbVO>
		<!--增值税专用发票##9%-->
		<fb1GridlbVO>
			<ewbhxh>21</ewbhxh>
			<!--增值税专用发票##9%##开具税控增值税专用发票##销售额-->
			<zzszyfp9kjskzzszyfpxse/>
			<!--增值税专用发票##9%##开具税控增值税专用发票##销项(应纳)税额-->
			<zzszyfp9kjskzzszyfpxxynse/>
		</fb1GridlbVO>
		<!--增值税专用发票##6%-->
		<fb1GridlbVO>
			<ewbhxh>22</ewbhxh>
			<!--增值税专用发票##6%##开具税控增值税专用发票##销项(应纳)税额-->
			<zzszyfp6kjskzzszyfpxxynse/>
			<!--增值税专用发票##6%##开具税控增值税专用发票##销售额-->
			<zzszyfp6kjskzzszyfpxse/>
		</fb1GridlbVO>
		<!--增值税专用发票##5%-->
		<fb1GridlbVO>
			<ewbhxh>23</ewbhxh>
			<!--增值税专用发票##5%##开具税控增值税专用发票##销项(应纳)税额-->
			<zzszyfp5kjskzzszyfpxxynse/>
			<!--增值税专用发票##5%##开具税控增值税专用发票##销售额-->
			<zzszyfp5kjskzzszyfpxse/>
		</fb1GridlbVO>
		<!--增值税专用发票##4%-->
		<fb1GridlbVO>
			<ewbhxh>24</ewbhxh>
			<!--增值税专用发票##4%##开具税控增值税专用发票##销售额-->
			<zzszyfp4kjskzzszyfpxse/>
			<!--增值税专用发票##4%##开具税控增值税专用发票##销项(应纳)税额-->
			<zzszyfp4kjskzzszyfpxxynse/>
		</fb1GridlbVO>
		<!--增值税专用发票##3%-->
		<fb1GridlbVO>
			<ewbhxh>25</ewbhxh>
			<!--增值税专用发票##3%##开具税控增值税专用发票##销项(应纳)税额-->
			<zzszyfp3kjskzzszyfpxxynse/>
			<!--增值税专用发票##3%##开具税控增值税专用发票##销售额-->
			<zzszyfp3kjskzzszyfpxse/>
		</fb1GridlbVO>
		<!--增值税专用发票##0%-->
		<fb1GridlbVO>
			<ewbhxh>26</ewbhxh>
			<!--增值税专用发票##0%##开具税控增值税专用发票##销项(应纳)税额-->
			<zzszyfp0kjskzzszyfpxxynse/>
			<!--增值税专用发票##0%##开具税控增值税专用发票##销售额-->
			<zzszyfp0kjskzzszyfpxse/>
		</fb1GridlbVO>
		<!--增值税普通发票##13%-->
		<fb1GridlbVO>
			<ewbhxh>27</ewbhxh>
			<!--增值税普通发票##13%##开具税控增值税专用发票##销项(应纳)税额-->
			<zzsptfp13kjskzzszyfpxxynse/>
			<!--增值税普通发票##13%##开具税控增值税专用发票##销售额-->
			<zzsptfp13kjskzzszyfpxse/>
		</fb1GridlbVO>
		<!--增值税普通发票##9%-->
		<fb1GridlbVO>
			<ewbhxh>28</ewbhxh>
			<!--增值税普通发票##9%##开具税控增值税专用发票##销项(应纳)税额-->
			<zzsptfp9kjskzzszyfpxxynse/>
			<!--增值税普通发票##9%##开具税控增值税专用发票##销售额-->
			<zzsptfp9kjskzzszyfpxse/>
		</fb1GridlbVO>
		<!--增值税普通发票##6%-->
		<fb1GridlbVO>
			<ewbhxh>29</ewbhxh>
			<!--增值税普通发票##6%##开具税控增值税专用发票##销项(应纳)税额-->
			<zzsptfp6kjskzzszyfpxxynse/>
			<!--增值税普通发票##6%##开具税控增值税专用发票##销售额-->
			<zzsptfp6kjskzzszyfpxse/>
		</fb1GridlbVO>
		<!--增值税普通发票##5%-->
		<fb1GridlbVO>
			<ewbhxh>30</ewbhxh>
			<!--增值税普通发票##5%##开具税控增值税专用发票##销项(应纳)税额-->
			<zzsptfp5kjskzzszyfpxxynse/>
			<!--增值税普通发票##5%##开具税控增值税专用发票##销售额-->
			<zzsptfp5kjskzzszyfpxse/>
		</fb1GridlbVO>
		<!--增值税普通发票##4%-->
		<fb1GridlbVO>
			<ewbhxh>31</ewbhxh>
			<!--增值税普通发票##4%##开具税控增值税专用发票##销售额-->
			<zzsptfp4kjskzzszyfpxse/>
			<!--增值税普通发票##4%##开具税控增值税专用发票##销项(应纳)税额-->
			<zzsptfp4kjskzzszyfpxxynse/>
		</fb1GridlbVO>
		<!--增值税普通发票##3%-->
		<fb1GridlbVO>
			<ewbhxh>32</ewbhxh>
			<!--增值税普通发票##3%##开具税控增值税专用发票##销项(应纳)税额-->
			<zzsptfp3kjskzzszyfpxxynse/>
			<!--增值税普通发票##3%##开具税控增值税专用发票##销售额-->
			<zzsptfp3kjskzzszyfpxse/>
		</fb1GridlbVO>
		<!--增值税普通发票##0%-->
		<fb1GridlbVO>
			<ewbhxh>33</ewbhxh>
			<!--增值税普通发票##0%##开具税控增值税专用发票##销项(应纳)税额-->
			<zzsptfp0kjskzzszyfpxxynse/>
			<!--增值税普通发票##0%##开具税控增值税专用发票##销售额-->
			<zzsptfp0kjskzzszyfpxse/>
		</fb1GridlbVO>	
		<!--一、一般计税方法计税##全部征税项目##13%税率  ##新增 江苏不需要传##-->
		<fb1GridlbVO>
			<ewbhxh>34</ewbhxh>
			<!--一、一般计税方法计税##全部征税项目##13%税率##开具税控增值税专用发票##销售额-->
			<yybjsffjsqbzsxm13slkjskzzszyfpxse/>
			<!--一、一般计税方法计税##全部征税项目##13%税率##纳税检查调整##销售额-->
			<yybjsffjsqbzsxm13slnsjcdzxse/>
			<!--一、一般计税方法计税##全部征税项目##13%税率##合计##销项(应纳)税额-->
			<yybjsffjsqbzsxm13slhjxxynse/>
			<!--一、一般计税方法计税##全部征税项目##13%税率##纳税检查调整##销项(应纳)税额-->
			<yybjsffjsqbzsxm13slnsjcdzxxynse/>
			<!--一、一般计税方法计税##全部征税项目##13%税率##开具税控增值税专用发票##销项(应纳)税额-->
			<yybjsffjsqbzsxm13slkjskzzszyfpxxynse/>
			<!--一、一般计税方法计税##全部征税项目##13%税率##开具其他发票##销项(应纳)税额-->
			<yybjsffjsqbzsxm13slkjqtfpxxynse/>
			<!--一、一般计税方法计税##全部征税项目##13%税率##未开具发票##销项(应纳)税额-->
			<yybjsffjsqbzsxm13slwkjfpxxynse/>
			<!--一、一般计税方法计税##全部征税项目##13%税率##合计##销售额-->
			<yybjsffjsqbzsxm13slhjxse/>
			<!--一、一般计税方法计税##全部征税项目##13%税率##开具其他发票##销售额-->
			<yybjsffjsqbzsxm13slkjqtfpxse/>
			<!--一、一般计税方法计税##全部征税项目##13%税率##未开具发票##销售额-->
			<yybjsffjsqbzsxm13slwkjfpxse/>
		</fb1GridlbVO>
		<!--二、简易计税方法计税##全部征税项目##预征率% 13a  ##新增 江苏不需要传##-->
		<fb1GridlbVO>
			<ewbhxh>35</ewbhxh>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13a##开具税控增值税专用发票##销售额-->
			<ejyjsffjsqbzsxmyzl13akjskzzszyfpxse/>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13a##未开具发票##销项(应纳)税额-->
			<ejyjsffjsqbzsxmyzl13awkjfpxxynse/>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13a##合计##销项(应纳)税额-->
			<ejyjsffjsqbzsxmyzl13ahjxxynse/>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13a##扣除后##含税(免税)销售额-->
			<ejyjsffjsqbzsxmyzl13akchhsmsxse/>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13a##合计##销售额-->
			<ejyjsffjsqbzsxmyzl13ahjxse/>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13a##未开具发票##销售额-->
			<ejyjsffjsqbzsxmyzl13awkjfpxse/>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13a##合计##价税合计-->
			<ejyjsffjsqbzsxmyzl13ahjjshj/>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13a##开具税控增值税专用发票##销项(应纳)税额-->
			<ejyjsffjsqbzsxmyzl13akjskzzszyfpxxynse/>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13a##应税服务扣除项目本期实际扣除金额##价税合计-->
			<ejyjsffjsqbzsxmyzl13aysfwkcxmbqsjkcjejshj/>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13a##开具其他发票##销项(应纳)税额-->
			<ejyjsffjsqbzsxmyzl13akjqtfpxxynse/>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13a##扣除后##销项(应纳)税额-->
			<ejyjsffjsqbzsxmyzl13akchxxynse/>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13a##开具其他发票##销售额-->
			<ejyjsffjsqbzsxmyzl13akjqtfpxse/>
		</fb1GridlbVO>
		<!--二、简易计税方法计税##全部征税项目##预征率% 13b  ##新增 江苏不需要传##-->
		<fb1GridlbVO>
			<ewbhxh>36</ewbhxh>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13b##开具税控增值税专用发票##销售额-->
			<ejyjsffjsqbzsxmyzl13bkjskzzszyfpxse/>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13b##未开具发票##销项(应纳)税额-->
			<ejyjsffjsqbzsxmyzl13bwkjfpxxynse/>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13b##合计##销项(应纳)税额-->
			<ejyjsffjsqbzsxmyzl13bhjxxynse/>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13b##扣除后##含税(免税)销售额-->
			<ejyjsffjsqbzsxmyzl13bkchhsmsxse/>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13b##合计##销售额-->
			<ejyjsffjsqbzsxmyzl13bhjxse/>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13b##未开具发票##销售额-->
			<ejyjsffjsqbzsxmyzl13bwkjfpxse/>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13b##合计##价税合计-->
			<ejyjsffjsqbzsxmyzl13bhjjshj/>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13b##开具税控增值税专用发票##销项(应纳)税额-->
			<ejyjsffjsqbzsxmyzl13bkjskzzszyfpxxynse/>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13b##应税服务扣除项目本期实际扣除金额##价税合计-->
			<ejyjsffjsqbzsxmyzl13bysfwkcxmbqsjkcjejshj/>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13b##开具其他发票##销项(应纳)税额-->
			<ejyjsffjsqbzsxmyzl13bkjqtfpxxynse/>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13b##扣除后##销项(应纳)税额-->
			<ejyjsffjsqbzsxmyzl13bkchxxynse/>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13b##开具其他发票##销售额-->
			<ejyjsffjsqbzsxmyzl13bkjqtfpxse/>
		</fb1GridlbVO>
		<!--二、简易计税方法计税##全部征税项目##预征率% 13c  ##新增 江苏不需要传##-->
		<fb1GridlbVO>
			<ewbhxh>37</ewbhxh>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13c##开具税控增值税专用发票##销售额-->
			<ejyjsffjsqbzsxmyzl13ckjskzzszyfpxse/>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13c##未开具发票##销项(应纳)税额-->
			<ejyjsffjsqbzsxmyzl13cwkjfpxxynse/>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13c##合计##销项(应纳)税额-->
			<ejyjsffjsqbzsxmyzl13chjxxynse/>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13c##扣除后##含税(免税)销售额-->
			<ejyjsffjsqbzsxmyzl13ckchhsmsxse/>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13c##合计##销售额-->
			<ejyjsffjsqbzsxmyzl13chjxse/>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13c##未开具发票##销售额-->
			<ejyjsffjsqbzsxmyzl13cwkjfpxse/>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13c##合计##价税合计-->
			<ejyjsffjsqbzsxmyzl13chjjshj/>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13c##开具税控增值税专用发票##销项(应纳)税额-->
			<ejyjsffjsqbzsxmyzl13ckjskzzszyfpxxynse/>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13c##应税服务扣除项目本期实际扣除金额##价税合计-->
			<ejyjsffjsqbzsxmyzl13cysfwkcxmbqsjkcjejshj/>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13c##开具其他发票##销项(应纳)税额-->
			<ejyjsffjsqbzsxmyzl13ckjqtfpxxynse/>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13c##扣除后##销项(应纳)税额-->
			<ejyjsffjsqbzsxmyzl13ckchxxynse/>
			<!--二、简易计税方法计税##全部征税项目##预征率% 13c##开具其他发票##销售额-->
			<ejyjsffjsqbzsxmyzl13ckjqtfpxse/>
		</fb1GridlbVO>		
	</jsxgs_zzs_ybnsr_fb1>
	<!-- 新国税增值税一般纳税人申报表 附表二 -->
	<jsxgs_zzs_ybnsr_fb2>
		<!--(一)认证相符的税控增值税专用发票1=2+3-->
		<fb2GridlbVO>
			<ewbhxh>1</ewbhxh>
			<!--(一)认证相符的税控增值税专用发票1=2+3##税额-->
			<yrzxfdskzzszyfp123se/>
			<!--(一)认证相符的税控增值税专用发票1=2+3##金额-->
			<yrzxfdskzzszyfp123je/>
			<!--(一)认证相符的税控增值税专用发票1=2+3##份数-->
			<yrzxfdskzzszyfp123fs/>
		</fb2GridlbVO>
		<!--其中：本期认证相符且本期申报抵扣-->
		<fb2GridlbVO>
			<ewbhxh>2</ewbhxh>
			<!--其中：本期认证相符且本期申报抵扣##金额-->
			<qzbqrzxfqbqsbdkje/>
			<!--其中：本期认证相符且本期申报抵扣##份数-->
			<qzbqrzxfqbqsbdkfs/>
			<!--其中：本期认证相符且本期申报抵扣##税额-->
			<qzbqrzxfqbqsbdkse/>
		</fb2GridlbVO>
		<!--前期认证相符且本期申报抵扣-->
		<fb2GridlbVO>
			<ewbhxh>3</ewbhxh>
			<!--前期认证相符且本期申报抵扣##税额-->
			<qqrzxfqbqsbdkse/>
			<!--前期认证相符且本期申报抵扣##金额-->
			<qqrzxfqbqsbdkje/>
			<!--前期认证相符且本期申报抵扣##份数-->
			<qqrzxfqbqsbdkfs/>
		</fb2GridlbVO>
		<!--(二)其他扣税凭证1-->
		<fb2GridlbVO>
			<ewbhxh>4</ewbhxh>
			<!--(二)其他扣税凭证1##金额-->
			<eqtkspz1je/>
			<!--(二)其他扣税凭证1##税额-->
			<eqtkspz1se/>
			<!--(二)其他扣税凭证1##份数-->
			<eqtkspz1fs/>
		</fb2GridlbVO>
		<!--其中：海关进口增值税专用缴款书-->
		<fb2GridlbVO>
			<ewbhxh>5</ewbhxh>
			<!--其中：海关进口增值税专用缴款书##金额-->
			<qzhgjkzzszyjksje/>
			<!--其中：海关进口增值税专用缴款书##税额-->
			<qzhgjkzzszyjksse/>
			<!--其中：海关进口增值税专用缴款书##份数-->
			<qzhgjkzzszyjksfs/>
		</fb2GridlbVO>
		<!--农产品收购发票或者销售发票-->
		<fb2GridlbVO>
			<ewbhxh>6</ewbhxh>
			<!--农产品收购发票或者销售发票##金额-->
			<ncpsgfphzxsfpje/>
			<!--农产品收购发票或者销售发票##税额-->
			<ncpsgfphzxsfpse/>
			<!--农产品收购发票或者销售发票##份数-->
			<ncpsgfphzxsfpfs/>
		</fb2GridlbVO>
		<!--代扣代缴税收缴款凭证-->
		<fb2GridlbVO>
			<ewbhxh>7</ewbhxh>
			<!--代扣代缴税收缴款凭证##份数-->
			<dkdjssjkpzfs/>
			<!--代扣代缴税收缴款凭证##税额-->
			<dkdjssjkpzse/>
		</fb2GridlbVO>
		<!--加计扣除农产品进项税额-->
		<fb2GridlbVO>
			<ewbhxh>8</ewbhxh>
			<!--加计扣除农产品进项税额##税额-->
			<jjkcncpjxsese/>
		</fb2GridlbVO>
		<!--其他-->
		<fb2GridlbVO>
			<ewbhxh>9</ewbhxh>
			<!--其他##金额-->
			<qtje/>
			<!--其他##税额-->
			<qtse/>
			<!--其他##份数-->
			<qtfs/>
		</fb2GridlbVO>
		<!--(三)本期用于购建不动产的扣税凭证-->
		<fb2GridlbVO>
			<ewbhxh>10</ewbhxh>
			<!--(三)本期用于购建不动产的扣税凭证##金额-->
			<sbqyygjbdcdkspzje/>
			<!--(三)本期用于购建不动产的扣税凭证##份数-->
			<sbqyygjbdcdkspzfs/>
			<!--(三)本期用于购建不动产的扣税凭证##税额-->
			<sbqyygjbdcdkspzse/>
		</fb2GridlbVO>
		<!--(四)本期用于抵扣的旅客运输服务扣税凭证-->
		<fb2GridlbVO>
			<ewbhxh>11</ewbhxh>
			<!--(四)本期用于抵扣的旅客运输服务扣税凭证##税额-->
			<sbqyydkdlkysfwkspzse/>
			<!--(四)本期用于抵扣的旅客运输服务扣税凭证##份数   ##新增 江苏不需要传##-->
			<sbqyydkdlkysfwkspzfs/>
			<!--(四)本期用于抵扣的旅客运输服务扣税凭证##金额   ##新增 江苏不需要传##-->
			<sbqyydkdlkysfwkspzje/>
		</fb2GridlbVO>
		<!--(五)外贸企业进项税额抵扣证明-->
		<fb2GridlbVO>
			<ewbhxh>12</ewbhxh>
			<!--(五)外贸企业进项税额抵扣证明##税额-->
			<wwmqyjxsedkzmse/>
		</fb2GridlbVO>
		<!--当期申报抵扣进项税额合计-->
		<fb2GridlbVO>
			<ewbhxh>13</ewbhxh>
			<!--当期申报抵扣进项税额合计##税额-->
			<dqsbdkjxsehjse/>
			<!--当期申报抵扣进项税额合计##金额-->
			<dqsbdkjxsehjje/>
			<!--当期申报抵扣进项税额合计##份数-->
			<dqsbdkjxsehjfs/>
		</fb2GridlbVO>
		<!--本期进项税转出额-->
		<fb2GridlbVO>
			<ewbhxh>14</ewbhxh>
			<!--本期进项税转出额##税额-->
			<bqjxszcese/>
		</fb2GridlbVO>
		<!--其中：免税项目用-->
		<fb2GridlbVO>
			<ewbhxh>15</ewbhxh>
			<!--其中：免税项目用##税额-->
			<qzmsxmyse/>
		</fb2GridlbVO>
		<!--集体福利、个人消费-->
		<fb2GridlbVO>
			<ewbhxh>16</ewbhxh>
			<!--集体福利、个人消费##税额-->
			<jtflgrxfse/>
		</fb2GridlbVO>
		<!--非正常损失-->
		<fb2GridlbVO>
			<ewbhxh>17</ewbhxh>
			<!--非正常损失##税额-->
			<fzcssse/>
		</fb2GridlbVO>
		<!--简易计税方法征税项目用-->
		<fb2GridlbVO>
			<ewbhxh>18</ewbhxh>
			<!--简易计税方法征税项目用##税额-->
			<jyjsffzsxmyse/>
		</fb2GridlbVO>
		<!--免抵退税办法不得抵扣的进项税额-->
		<fb2GridlbVO>
			<ewbhxh>19</ewbhxh>
			<!--免抵退税办法不得抵扣的进项税额##税额-->
			<mdtsbfbddkdjxsese/>
		</fb2GridlbVO>
		<!--纳税检查调减进项税额-->
		<fb2GridlbVO>
			<ewbhxh>20</ewbhxh>
			<!--纳税检查调减进项税额##税额-->
			<nsjcdjjxsese/>
		</fb2GridlbVO>
		<!--红字专用发票通知单注明的进项税额-->
		<fb2GridlbVO>
			<ewbhxh>21</ewbhxh>
			<!--红字专用发票通知单注明的进项税额##税额-->
			<hzzyfptzdzmdjxsese/>
		</fb2GridlbVO>
		<!--上期留抵税额抵减欠税-->
		<fb2GridlbVO>
			<ewbhxh>22</ewbhxh>
			<!--上期留抵税额抵减欠税##税额-->
			<sqldsedjqsse/>
		</fb2GridlbVO>
		<!--上期留抵税额退税-->
		<fb2GridlbVO>
			<ewbhxh>23</ewbhxh>
			<!--上期留抵税额退税##税额-->
			<sqldsetsse/>
		</fb2GridlbVO>
		<!--其他应作进项税额转出的情形-->
		<fb2GridlbVO>
			<ewbhxh>24</ewbhxh>
			<!--其他应作进项税额转出的情形##税额-->
			<qtyzjxsezcdqxse/>
		</fb2GridlbVO>
		<!--期初已认证相符但未申报抵扣-->
		<fb2GridlbVO>
			<ewbhxh>25</ewbhxh>
			<!--期初已认证相符但未申报抵扣##税额##税额-->
			<qcyrzxfdwsbdksese/>
			<!--期初已认证相符但未申报抵扣##税额##金额-->
			<qcyrzxfdwsbdkseje/>
			<!--期初已认证相符但未申报抵扣##份数-->
			<qcyrzxfdwsbdkfs/>
		</fb2GridlbVO>
		<!--本期认证相符且本期未申报抵扣-->
		<fb2GridlbVO>
			<ewbhxh>26</ewbhxh>
			<!--本期认证相符且本期未申报抵扣##份数-->
			<bqrzxfqbqwsbdkfs/>
			<!--本期认证相符且本期未申报抵扣##税额##金额-->
			<bqrzxfqbqwsbdkseje/>
			<!--本期认证相符且本期未申报抵扣##税额##税额-->
			<bqrzxfqbqwsbdksese/>
		</fb2GridlbVO>
		<!--期末已认证相符但未申报抵扣-->
		<fb2GridlbVO>
			<ewbhxh>27</ewbhxh>
			<!--期末已认证相符但未申报抵扣##份数-->
			<qmyrzxfdwsbdkfs/>
			<!--期末已认证相符但未申报抵扣##税额##税额-->
			<qmyrzxfdwsbdksese/>
			<!--期末已认证相符但未申报抵扣##税额##金额-->
			<qmyrzxfdwsbdkseje/>
		</fb2GridlbVO>
		<!--其中：按照税法规定不允许抵扣-->
		<fb2GridlbVO>
			<ewbhxh>28</ewbhxh>
			<!--其中：按照税法规定不允许抵扣##税额##金额-->
			<qzazsfgdbyxdkseje/>
			<!--其中：按照税法规定不允许抵扣##税额##税额-->
			<qzazsfgdbyxdksese/>
			<!--其中：按照税法规定不允许抵扣##份数-->
			<qzazsfgdbyxdkfs/>
		</fb2GridlbVO>
		<!--(二)其他扣税凭证-->
		<fb2GridlbVO>
			<ewbhxh>29</ewbhxh>
			<!--(二)其他扣税凭证##税额##税额-->
			<eqtkspzsese/>
			<!--(二)其他扣税凭证##份数-->
			<eqtkspzfs/>
			<!--(二)其他扣税凭证##税额##金额-->
			<eqtkspzseje/>
		</fb2GridlbVO>
		<!--其中：海关进口增值税专用缴款书1-->
		<fb2GridlbVO>
			<ewbhxh>30</ewbhxh>
			<!--其中：海关进口增值税专用缴款书1##份数-->
			<qzhgjkzzszyjks1fs/>
			<!--其中：海关进口增值税专用缴款书1##税额##税额-->
			<qzhgjkzzszyjks1sese/>
			<!--其中：海关进口增值税专用缴款书1##税额##金额-->
			<qzhgjkzzszyjks1seje/>
		</fb2GridlbVO>
		<!--农产品收购发票或者销售发票1-->
		<fb2GridlbVO>
			<ewbhxh>31</ewbhxh>
			<!--农产品收购发票或者销售发票1##税额##金额-->
			<ncpsgfphzxsfp1seje/>
			<!--农产品收购发票或者销售发票1##份数-->
			<ncpsgfphzxsfp1fs/>
			<!--农产品收购发票或者销售发票1##税额##税额-->
			<ncpsgfphzxsfp1sese/>
		</fb2GridlbVO>
		<!--代扣代缴税收缴款凭证1-->
		<fb2GridlbVO>
			<ewbhxh>32</ewbhxh>
			<!--代扣代缴税收缴款凭证1##税额##税额-->
			<dkdjssjkpz1sese/>
			<!--代扣代缴税收缴款凭证1##份数-->
			<dkdjssjkpz1fs/>
		</fb2GridlbVO>
		<!--其他1-->
		<fb2GridlbVO>
			<ewbhxh>33</ewbhxh>
			<!--其他1##份数-->
			<qt1fs/>
			<!--其他1##税额##金额-->
			<qt1seje/>
			<!--其他1##税额##税额-->
			<qt1sese/>
		</fb2GridlbVO>
		<!--本期认证相符的税控增值税专用发票-->
		<fb2GridlbVO>
			<ewbhxh>34</ewbhxh>
			<!--本期认证相符的税控增值税专用发票##份数-->
			<bqrzxfdskzzszyfpfs/>
			<!--本期认证相符的税控增值税专用发票##金额-->
			<bqrzxfdskzzszyfpje/>
			<!--本期认证相符的税控增值税专用发票##税额-->
			<bqrzxfdskzzszyfpse/>
		</fb2GridlbVO>
		<!--代扣代缴税额 ##新增 江苏不需要传## -->
		<fb2GridlbVO>
			<ewbhxh>35</ewbhxh>
			<!--代扣代缴税额##税额-->
			<dkdjse/>
		</fb2GridlbVO>
	</jsxgs_zzs_ybnsr_fb2>
	<!-- 新国税增值税一般纳税人申报表 附表四 -->
	<jsxgs_zzs_ybnsr_fb4>
		<!--增值税税控系统专用设备费及技术维护费-->
		<fb4GridlbVO>
			<ewbhxh>1</ewbhxh>
			<!--增值税税控系统专用设备费及技术维护费##本期实际抵减税额-->
			<zzsskxtzysbfjjswhfbqsjdjse/>
			<!--增值税税控系统专用设备费及技术维护费##期初余额-->
			<zzsskxtzysbfjjswhfqcye/>
			<!--增值税税控系统专用设备费及技术维护费##本期发生额-->
			<zzsskxtzysbfjjswhfbqfse/>
			<!--增值税税控系统专用设备费及技术维护费##本期应抵减税额-->
			<zzsskxtzysbfjjswhfbqydjse/>
			<!--增值税税控系统专用设备费及技术维护费##期末余额-->
			<zzsskxtzysbfjjswhfqmye/>
		</fb4GridlbVO>
		<!--分支机构预征缴纳税款-->
		<fb4GridlbVO>
			<ewbhxh>2</ewbhxh>
			<!--分支机构预征缴纳税款##期初余额-->
			<fzjgyzjnskqcye/>
			<!--分支机构预征缴纳税款##本期发生额-->
			<fzjgyzjnskbqfse/>
			<!--分支机构预征缴纳税款##本期实际抵减税额-->
			<fzjgyzjnskbqsjdjse/>
			<!--分支机构预征缴纳税款##本期应抵减税额-->
			<fzjgyzjnskbqydjse/>
			<!--分支机构预征缴纳税款##期末余额-->
			<fzjgyzjnskqmye/>
		</fb4GridlbVO>
		<!--建筑服务预征缴纳税款-->
		<fb4GridlbVO>
			<ewbhxh>3</ewbhxh>
			<!--建筑服务预征缴纳税款##期初余额-->
			<jzfwyzjnskqcye/>
			<!--建筑服务预征缴纳税款##本期应抵减税额-->
			<jzfwyzjnskbqydjse/>
			<!--建筑服务预征缴纳税款##本期实际抵减税额-->
			<jzfwyzjnskbqsjdjse/>
			<!--建筑服务预征缴纳税款##本期发生额-->
			<jzfwyzjnskbqfse/>
			<!--建筑服务预征缴纳税款##期末余额-->
			<jzfwyzjnskqmye/>
		</fb4GridlbVO>
		<!--销售不动产预征缴纳税款-->
		<fb4GridlbVO>
			<ewbhxh>4</ewbhxh>
			<!--销售不动产预征缴纳税款##本期实际抵减税额-->
			<xsbdcyzjnskbqsjdjse/>
			<!--销售不动产预征缴纳税款##期初余额-->
			<xsbdcyzjnskqcye/>
			<!--销售不动产预征缴纳税款##本期发生额-->
			<xsbdcyzjnskbqfse/>
			<!--销售不动产预征缴纳税款##本期应抵减税额-->
			<xsbdcyzjnskbqydjse/>
			<!--销售不动产预征缴纳税款##期末余额-->
			<xsbdcyzjnskqmye/>
		</fb4GridlbVO>
		<!--出租不动产预征缴纳税款-->
		<fb4GridlbVO>
			<ewbhxh>5</ewbhxh>
			<!--出租不动产预征缴纳税款##期初余额-->
			<czbdcyzjnskqcye/>
			<!--出租不动产预征缴纳税款##本期实际抵减税额-->
			<czbdcyzjnskbqsjdjse/>
			<!--出租不动产预征缴纳税款##本期应抵减税额-->
			<czbdcyzjnskbqydjse/>
			<!--出租不动产预征缴纳税款##本期发生额-->
			<czbdcyzjnskbqfse/>
			<!--出租不动产预征缴纳税款##期末余额-->
			<czbdcyzjnskqmye/>
		</fb4GridlbVO>
		<!--一般项目加计抵减额计算-->
		<fb4GridlbVO>
			<ewbhxh>6</ewbhxh>
			<!--一般项目加计抵减额计算##本期应抵减税额##本期调减额-->
			<ybxmjjdjejsbqydjsebqdje/>
			<!--一般项目加计抵减额计算##期末余额##本期实际抵减额-->
			<ybxmjjdjejsqmyebqsjdje/>
			<!--一般项目加计抵减额计算##本期发生额-->
			<ybxmjjdjejsbqfse/>
			<!--一般项目加计抵减额计算##期初余额-->
			<ybxmjjdjejsqcye/>
			<!--一般项目加计抵减额计算##本期实际抵减税额##本期可抵减额-->
			<ybxmjjdjejsbqsjdjsebqkdje/>
			<!--一般项目加计抵减额计算##期末余额##期末余额-->
			<ybxmjjdjejsqmyeqmye/>
		</fb4GridlbVO>
		<!--即征即退项目加计抵减额计算-->
		<fb4GridlbVO>
			<ewbhxh>7</ewbhxh>
			<!--即征即退项目加计抵减额计算##本期实际抵减税额##本期可抵减额-->
			<jzjtxmjjdjejsbqsjdjsebqkdje/>
			<!--即征即退项目加计抵减额计算##期末余额##本期实际抵减额-->
			<jzjtxmjjdjejsqmyebqsjdje/>
			<!--即征即退项目加计抵减额计算##期末余额##期末余额-->
			<jzjtxmjjdjejsqmyeqmye/>
			<!--即征即退项目加计抵减额计算##本期应抵减税额##本期调减额-->
			<jzjtxmjjdjejsbqydjsebqdje/>
			<!--即征即退项目加计抵减额计算##期初余额-->
			<jzjtxmjjdjejsqcye/>
			<!--即征即退项目加计抵减额计算##本期发生额-->
			<jzjtxmjjdjejsbqfse/>
		</fb4GridlbVO>
		<!--合计-->
		<fb4GridlbVO>
			<ewbhxh>8</ewbhxh>
			<!--合计##本期应抵减税额##本期调减额-->
			<hjbqydjsebqdje/>
			<!--合计##本期发生额-->
			<hjbqfse/>
			<!--合计##期末余额##本期实际抵减额-->
			<hjqmyebqsjdje/>
			<!--合计##本期实际抵减税额##本期可抵减额-->
			<hjbqsjdjsebqkdje/>
			<!--合计##期末余额##期末余额-->
			<hjqmyeqmye/>
			<!--合计##期初余额-->
			<hjqcye/>
		</fb4GridlbVO>
	</jsxgs_zzs_ybnsr_fb4>
	<!-- 新国税增值税一般纳税人申报表 附表三 -->
	<jsxgs_zzs_ybnsr_fb3>
		<!--13%税率的有形动产租赁服务-->
		<fb3GridlbVO>
			<ewbhxh>1</ewbhxh>
			<!--13%税率的有形动产租赁服务##应税服务扣除项目##本期实际扣除金额-->
			<sldyxdczlfwysfwkcxmbqsjkcje/>
			<!--13%税率的有形动产租赁服务##应税服务扣除项目##期初余额-->
			<sldyxdczlfwysfwkcxmqcye/>
			<!--13%税率的有形动产租赁服务##应税服务扣除项目##期末余额-->
			<sldyxdczlfwysfwkcxmqmye/>
			<!--13%税率的有形动产租赁服务##应税服务扣除项目##本期发生额-->
			<sldyxdczlfwysfwkcxmbqfse/>
			<!--13%税率的有形动产租赁服务##应税服务扣除项目##本期应扣除金额-->
			<sldyxdczlfwysfwkcxmbqykcje/>
			<!--13%税率的有形动产租赁服务##本期应税服务价税合计额(免税销售额)-->
			<sldyxdczlfwbqysfwjshjemsxse/>
		</fb3GridlbVO>
		<!--9%税率的应税服务-->
		<fb3GridlbVO>
			<ewbhxh>2</ewbhxh>
			<!--9%税率的应税服务##本期应税服务价税合计额(免税销售额)-->
			<sldysfwbqysfwjshjemsxse/>
			<!--9%税率的应税服务##应税服务扣除项目##期初余额-->
			<sldysfwysfwkcxmqcye/>
			<!--9%税率的应税服务##应税服务扣除项目##期末余额-->
			<sldysfwysfwkcxmqmye/>
			<!--9%税率的应税服务##应税服务扣除项目##本期发生额-->
			<sldysfwysfwkcxmbqfse/>
			<!--9%税率的应税服务##应税服务扣除项目##本期应扣除金额-->
			<sldysfwysfwkcxmbqykcje/>
			<!--9%税率的应税服务##应税服务扣除项目##本期实际扣除金额-->
			<sldysfwysfwkcxmbqsjkcje/>
		</fb3GridlbVO>
		<!--6%税率的应税服务(不含金融商品转让)-->
		<fb3GridlbVO>
			<ewbhxh>3</ewbhxh>
			<!--6%税率的应税服务(不含金融商品转让)##应税服务扣除项目##本期发生额-->
			<sldysfwbhjrspzrysfwkcxmbqfse/>
			<!--6%税率的应税服务(不含金融商品转让)##应税服务扣除项目##本期实际扣除金额-->
			<sldysfwbhjrspzrysfwkcxmbqsjkcje/>
			<!--6%税率的应税服务(不含金融商品转让)##应税服务扣除项目##期初余额-->
			<sldysfwbhjrspzrysfwkcxmqcye/>
			<!--6%税率的应税服务(不含金融商品转让)##应税服务扣除项目##本期应扣除金额-->
			<sldysfwbhjrspzrysfwkcxmbqykcje/>
			<!--6%税率的应税服务(不含金融商品转让)##应税服务扣除项目##期末余额-->
			<sldysfwbhjrspzrysfwkcxmqmye/>
			<!--6%税率的应税服务(不含金融商品转让)##本期应税服务价税合计额(免税销售额)-->
			<sldysfwbhjrspzrbqysfwjshjemsxse/>
		</fb3GridlbVO>
		<!--6%税率的金融商品转让项目-->
		<fb3GridlbVO>
			<ewbhxh>4</ewbhxh>
			<!--6%税率的金融商品转让项目##应税服务扣除项目##本期应扣除金额-->
			<sldjrspzrxmysfwkcxmbqykcje/>
			<!--6%税率的金融商品转让项目##本期应税服务价税合计额(免税销售额)-->
			<sldjrspzrxmbqysfwjshjemsxse/>
			<!--6%税率的金融商品转让项目##应税服务扣除项目##本期实际扣除金额-->
			<sldjrspzrxmysfwkcxmbqsjkcje/>
			<!--6%税率的金融商品转让项目##应税服务扣除项目##期初余额-->
			<sldjrspzrxmysfwkcxmqcye/>
			<!--6%税率的金融商品转让项目##应税服务扣除项目##本期发生额-->
			<sldjrspzrxmysfwkcxmbqfse/>
			<!--6%税率的金融商品转让项目##应税服务扣除项目##期末余额-->
			<sldjrspzrxmysfwkcxmqmye/>
		</fb3GridlbVO>
		<!--5%征收率的项目-->
		<fb3GridlbVO>
			<ewbhxh>5</ewbhxh>
			<!--5%征收率的项目##应税服务扣除项目##本期实际扣除金额-->
			<zsldxmysfwkcxmbqsjkcje/>
			<!--5%征收率的项目##应税服务扣除项目##期末余额-->
			<zsldxmysfwkcxmqmye/>
			<!--5%征收率的项目##应税服务扣除项目##本期发生额-->
			<zsldxmysfwkcxmbqfse/>
			<!--5%征收率的项目##应税服务扣除项目##本期应扣除金额-->
			<zsldxmysfwkcxmbqykcje/>
			<!--5%征收率的项目##应税服务扣除项目##期初余额-->
			<zsldxmysfwkcxmqcye/>
			<!--5%征收率的项目##本期应税服务价税合计额(免税销售额)-->
			<zsldxmbqysfwjshjemsxse/>
		</fb3GridlbVO>
		<!--3%征收率的应税服务-->
		<fb3GridlbVO>
			<ewbhxh>6</ewbhxh>
			<!--3%征收率的应税服务##应税服务扣除项目##期初余额-->
			<zsldysfwysfwkcxmqcye/>
			<!--3%征收率的应税服务##应税服务扣除项目##本期应扣除金额-->
			<zsldysfwysfwkcxmbqykcje/>
			<!--3%征收率的应税服务##应税服务扣除项目##本期实际扣除金额-->
			<zsldysfwysfwkcxmbqsjkcje/>
			<!--3%征收率的应税服务##应税服务扣除项目##期末余额-->
			<zsldysfwysfwkcxmqmye/>
			<!--3%征收率的应税服务##本期应税服务价税合计额(免税销售额)-->
			<zsldysfwbqysfwjshjemsxse/>
			<!--3%征收率的应税服务##应税服务扣除项目##本期发生额-->
			<zsldysfwysfwkcxmbqfse/>
		</fb3GridlbVO>
		<!--免抵退税的应税服务-->
		<fb3GridlbVO>
			<ewbhxh>7</ewbhxh>
			<!--免抵退税的应税服务##应税服务扣除项目##本期实际扣除金额-->
			<mdtsdysfwysfwkcxmbqsjkcje/>
			<!--免抵退税的应税服务##本期应税服务价税合计额(免税销售额)-->
			<mdtsdysfwbqysfwjshjemsxse/>
			<!--免抵退税的应税服务##应税服务扣除项目##本期发生额-->
			<mdtsdysfwysfwkcxmbqfse/>
			<!--免抵退税的应税服务##应税服务扣除项目##期初余额-->
			<mdtsdysfwysfwkcxmqcye/>
			<!--免抵退税的应税服务##应税服务扣除项目##期末余额-->
			<mdtsdysfwysfwkcxmqmye/>
			<!--免抵退税的应税服务##应税服务扣除项目##本期应扣除金额-->
			<mdtsdysfwysfwkcxmbqykcje/>
		</fb3GridlbVO>
		<!--免税的应税服务-->
		<fb3GridlbVO>
			<ewbhxh>8</ewbhxh>
			<!--免税的应税服务##应税服务扣除项目##本期应扣除金额-->
			<msdysfwysfwkcxmbqykcje/>
			<!--免税的应税服务##应税服务扣除项目##本期实际扣除金额-->
			<msdysfwysfwkcxmbqsjkcje/>
			<!--免税的应税服务##应税服务扣除项目##期初余额-->
			<msdysfwysfwkcxmqcye/>
			<!--免税的应税服务##本期应税服务价税合计额(免税销售额)-->
			<msdysfwbqysfwjshjemsxse/>
			<!--免税的应税服务##应税服务扣除项目##本期发生额-->
			<msdysfwysfwkcxmbqfse/>
			<!--免税的应税服务##应税服务扣除项目##期末余额-->
			<msdysfwysfwkcxmqmye/>
		</fb3GridlbVO>
	</jsxgs_zzs_ybnsr_fb3>
	<!-- 新国税增值税一般纳税人申报表 代扣代缴税收通用缴款书抵扣清单 -->
	<jsxgs_zzs_ybnsr_dkdj>
		<!--0_floating_r5_-->
		<dkdjGridlbVO>
			<ewbhxh>1</ewbhxh>
			<floatrow>1</floatrow>
			<!--0_floating_r5_##代扣代缴凭证编号-->
			<dkdjpzbh/>
			<!--0_floating_r5_##扣缴人名称-->
			<kjrmc/>
			<!--0_floating_r5_##税额-->
			<se/>
			<!--0_floating_r5_##扣缴纳税人识别号-->
			<kjnsrsbh/>
			<!--0_floating_r5_##代扣代缴项目-->
			<dkdjxm/>
			<!--0_floating_r5_##征收机关名称-->
			<zsjgmc/>
		</dkdjGridlbVO>
	</jsxgs_zzs_ybnsr_dkdj>
	<!-- 新国税增值税一般纳税人申报表 成品油购销存情况明细表 -->
	<jsxgs_zzs_ybnsr_cpygxcmxb>
		<!--1-->
		<cpygxcmxbGridlbVO>
			<ewbhxh>1</ewbhxh>
			<!--15-->
			<qmkcslzg/>
			<!--期初库存##数量##代储-->
			<qckcsldc/>
			<!--本期入库##金额##自购-->
			<bqrkjezg/>
			<!--5-->
			<bqrkslzg/>
			<!--期初库存##金额##自购-->
			<qckcjezg/>
			<!--期末库存##金额##自购-->
			<qmkcjezg/>
			<!--期末库存##数量##代储-->
			<qmkcsldc/>
			<!--1-->
			<qckcslzg/>
			<!--本期入库##数量##代储-->
			<bqrksldc/>
			<!--本期出库##非应税部分##金额##自用-->
			<bqckyssl/>
			<!--油品 型号-->
			<ypxh/>
			<!--本期出库##非应税部分##数量##代储-->
			<bqckfyssldc/>
			<!--本期出库##非应税部分##数量##自用-->
			<bqckfysslzy/>
			<!--9-->
			<bqchyssl/>
			<!--本期出库##应税部分##数量##金额-->
			<bqchysje/>
		</cpygxcmxbGridlbVO>
		<!--2-->
		<cpygxcmxbGridlbVO>
			<ewbhxh>2</ewbhxh>
			<!--期末库存##金额##自购-->
			<qmkcjezg/>
			<!--1-->
			<qckcslzg/>
			<!--15-->
			<qmkcslzg/>
			<!--期末库存##数量##代储-->
			<qmkcsldc/>
			<!--本期出库##非应税部分##金额##自用-->
			<bqckyssl/>
			<!--本期出库##非应税部分##数量##自用-->
			<bqckfysslzy/>
			<!--本期出库##非应税部分##数量##代储-->
			<bqckfyssldc/>
			<!--本期出库##应税部分##数量##金额-->
			<bqchysje/>
			<!--9-->
			<bqchyssl/>
			<!--5-->
			<bqrkslzg/>
			<!--期初库存##数量##代储-->
			<qckcsldc/>
			<!--油品 型号-->
			<ypxh/>
			<!--期初库存##金额##自购-->
			<qckcjezg/>
			<!--本期入库##数量##代储-->
			<bqrksldc/>
			<!--本期入库##金额##自购-->
			<bqrkjezg/>
		</cpygxcmxbGridlbVO>
		<!--3-->
		<cpygxcmxbGridlbVO>
			<ewbhxh>3</ewbhxh>
			<!--本期出库##应税部分##数量##金额-->
			<bqchysje/>
			<!--本期出库##非应税部分##数量##自用-->
			<bqckfysslzy/>
			<!--本期出库##非应税部分##数量##代储-->
			<bqckfyssldc/>
			<!--本期出库##非应税部分##金额##自用-->
			<bqckyssl/>
			<!--1-->
			<qckcslzg/>
			<!--期末库存##数量##代储-->
			<qmkcsldc/>
			<!--期末库存##金额##自购-->
			<qmkcjezg/>
			<!--本期入库##数量##代储-->
			<bqrksldc/>
			<!--5-->
			<bqrkslzg/>
			<!--本期入库##金额##自购-->
			<bqrkjezg/>
			<!--15-->
			<qmkcslzg/>
			<!--期初库存##数量##代储-->
			<qckcsldc/>
			<!--油品 型号-->
			<ypxh/>
			<!--9-->
			<bqchyssl/>
			<!--期初库存##金额##自购-->
			<qckcjezg/>
		</cpygxcmxbGridlbVO>
		<!--4-->
		<cpygxcmxbGridlbVO>
			<ewbhxh>4</ewbhxh>
			<!--期初库存##数量##代储-->
			<qckcsldc/>
			<!--期初库存##金额##自购-->
			<qckcjezg/>
			<!--15-->
			<qmkcslzg/>
			<!--本期入库##数量##代储-->
			<bqrksldc/>
			<!--1-->
			<qckcslzg/>
			<!--本期入库##金额##自购-->
			<bqrkjezg/>
			<!--本期出库##应税部分##数量##金额-->
			<bqchysje/>
			<!--本期出库##非应税部分##金额##自用-->
			<bqckyssl/>
			<!--本期出库##非应税部分##数量##自用-->
			<bqckfysslzy/>
			<!--本期出库##非应税部分##数量##代储-->
			<bqckfyssldc/>
			<!--期末库存##金额##自购-->
			<qmkcjezg/>
			<!--期末库存##数量##代储-->
			<qmkcsldc/>
			<!--5-->
			<bqrkslzg/>
			<!--油品 型号-->
			<ypxh/>
			<!--9-->
			<bqchyssl/>
		</cpygxcmxbGridlbVO>
		<!--5-->
		<cpygxcmxbGridlbVO>
			<ewbhxh>5</ewbhxh>
			<!--油品 型号-->
			<ypxh/>
			<!--本期入库##数量##代储-->
			<bqrksldc/>
			<!--期初库存##金额##自购-->
			<qckcjezg/>
			<!--本期出库##非应税部分##金额##自用-->
			<bqckyssl/>
			<!--本期出库##非应税部分##数量##代储-->
			<bqckfyssldc/>
			<!--1-->
			<qckcslzg/>
			<!--期初库存##数量##代储-->
			<qckcsldc/>
			<!--期末库存##金额##自购-->
			<qmkcjezg/>
			<!--期末库存##数量##代储-->
			<qmkcsldc/>
			<!--本期入库##金额##自购-->
			<bqrkjezg/>
			<!--15-->
			<qmkcslzg/>
			<!--5-->
			<bqrkslzg/>
			<!--本期出库##非应税部分##数量##自用-->
			<bqckfysslzy/>
			<!--9-->
			<bqchyssl/>
			<!--本期出库##应税部分##数量##金额-->
			<bqchysje/>
		</cpygxcmxbGridlbVO>
		<!--6-->
		<cpygxcmxbGridlbVO>
			<ewbhxh>6</ewbhxh>
			<!--1-->
			<qckcslzg/>
			<!--本期入库##金额##自购-->
			<bqrkjezg/>
			<!--本期入库##数量##代储-->
			<bqrksldc/>
			<!--5-->
			<bqrkslzg/>
			<!--本期出库##应税部分##数量##金额-->
			<bqchysje/>
			<!--本期出库##非应税部分##数量##代储-->
			<bqckfyssldc/>
			<!--本期出库##非应税部分##数量##自用-->
			<bqckfysslzy/>
			<!--15-->
			<qmkcslzg/>
			<!--期初库存##金额##自购-->
			<qckcjezg/>
			<!--期初库存##数量##代储-->
			<qckcsldc/>
			<!--期末库存##金额##自购-->
			<qmkcjezg/>
			<!--本期出库##非应税部分##金额##自用-->
			<bqckyssl/>
			<!--期末库存##数量##代储-->
			<qmkcsldc/>
			<!--9-->
			<bqchyssl/>
			<!--油品 型号-->
			<ypxh/>
		</cpygxcmxbGridlbVO>
		<!--7-->
		<cpygxcmxbGridlbVO>
			<ewbhxh>7</ewbhxh>
			<!--1-->
			<qckcslzg/>
			<!--期末库存##金额##自购-->
			<qmkcjezg/>
			<!--期末库存##数量##代储-->
			<qmkcsldc/>
			<!--5-->
			<bqrkslzg/>
			<!--期初库存##数量##代储-->
			<qckcsldc/>
			<!--期初库存##金额##自购-->
			<qckcjezg/>
			<!--本期出库##非应税部分##金额##自用-->
			<bqckyssl/>
			<!--本期入库##数量##代储-->
			<bqrksldc/>
			<!--本期出库##非应税部分##数量##代储-->
			<bqckfyssldc/>
			<!--本期入库##金额##自购-->
			<bqrkjezg/>
			<!--本期出库##非应税部分##数量##自用-->
			<bqckfysslzy/>
			<!--9-->
			<bqchyssl/>
			<!--本期出库##应税部分##数量##金额-->
			<bqchysje/>
			<!--油品 型号-->
			<ypxh/>
			<!--15-->
			<qmkcslzg/>
		</cpygxcmxbGridlbVO>
		<!--8-->
		<cpygxcmxbGridlbVO>
			<ewbhxh>8</ewbhxh>
			<!--1-->
			<qckcslzg/>
			<!--本期出库##应税部分##数量##金额-->
			<bqchysje/>
			<!--本期出库##非应税部分##数量##自用-->
			<bqckfysslzy/>
			<!--本期出库##非应税部分##数量##代储-->
			<bqckfyssldc/>
			<!--本期出库##非应税部分##金额##自用-->
			<bqckyssl/>
			<!--5-->
			<bqrkslzg/>
			<!--15-->
			<qmkcslzg/>
			<!--期初库存##数量##代储-->
			<qckcsldc/>
			<!--期初库存##金额##自购-->
			<qckcjezg/>
			<!--期末库存##数量##代储-->
			<qmkcsldc/>
			<!--期末库存##金额##自购-->
			<qmkcjezg/>
			<!--9-->
			<bqchyssl/>
			<!--油品 型号-->
			<ypxh/>
			<!--本期入库##数量##代储-->
			<bqrksldc/>
			<!--本期入库##金额##自购-->
			<bqrkjezg/>
		</cpygxcmxbGridlbVO>
		<!--合计-->
		<cpygxcmxbGridlbVO>
			<ewbhxh>9</ewbhxh>
			<!--9-->
			<bqchyssl/>
			<!--本期出库##应税部分##数量##金额-->
			<bqchysje/>
			<!--本期出库##非应税部分##数量##自用-->
			<bqckfysslzy/>
			<!--15-->
			<qmkcslzg/>
			<!--期初库存##数量##代储-->
			<qckcsldc/>
			<!--本期出库##非应税部分##数量##代储-->
			<bqckfyssldc/>
			<!--本期出库##非应税部分##金额##自用-->
			<bqckyssl/>
			<!--期初库存##金额##自购-->
			<qckcjezg/>
			<!--本期入库##数量##代储-->
			<bqrksldc/>
			<!--本期入库##金额##自购-->
			<bqrkjezg/>
			<!--1-->
			<qckcslzg/>
			<!--期末库存##数量##代储-->
			<qmkcsldc/>
			<!--期末库存##金额##自购-->
			<qmkcjezg/>
			<!--5-->
			<bqrkslzg/>
		</cpygxcmxbGridlbVO>
	</jsxgs_zzs_ybnsr_cpygxcmxb>
	<!-- 新国税增值税一般纳税人申报表 增值税减免税申报明细表 -->
	<jsxgs_zzs_ybnsr_jmsmxb>
		<!--1-->
		<jmsmxbGridlbVO>
			<ewbhxh>1</ewbhxh>
			<!--减税项目 ##增值税减免税申报明细表##期初余额-->
			<zzsjmssbmxbqcye/>
			<!--减税项目##增值税减免税申报明细表##本期实际抵减税额-->
			<zzsjmssbmxbbqsjdjse/>
			<!--减税项目##增值税减免税申报明细表##期末余额-->
			<zzsjmssbmxbqmye/>
			<!--减税项目##增值税减免税申报明细表##减税性质代码及名称-->
			<zzsjmssbmxbjsxzdmjmc/>
			<!--减税项目##增值税减免税申报明细表##本期应抵减税额-->
			<zzsjmssbmxbbqydjse/>
			<!--减税项目##增值税减免税申报明细表##本期发生额-->
			<zzsjmssbmxbbqfse/>
		</jmsmxbGridlbVO>
		<!--2-->
		<jmsmxbGridlbVO>
			<ewbhxh>2</ewbhxh> <!-- 减税项目 如果有多行的话 ewbhxh 往后追加/目前最多只遇到2行 -->
			<!--减税项目##增值税减免税申报明细表##期末余额-->
			<zzsjmssbmxbqmye/>
			<!--减税项目##增值税减免税申报明细表##减税性质代码及名称-->
			<zzsjmssbmxbjsxzdmjmc/>
			<!--减税项目##增值税减免税申报明细表##本期应抵减税额-->
			<zzsjmssbmxbbqydjse/>
			<!--减税项目##增值税减免税申报明细表##本期发生额-->
			<zzsjmssbmxbbqfse/>
			<!--减税项目##增值税减免税申报明细表##本期实际抵减税额-->
			<zzsjmssbmxbbqsjdjse/>
			<!--减税项目##增值税减免税申报明细表##期初余额-->
			<zzsjmssbmxbqcye/>
		</jmsmxbGridlbVO>
		<!--2##出口免税-->
		<jmsmxbGridlbVO>
			<ewbhxh>3</ewbhxh>
			<!--免税项目##出口免税##增值税减免税申报明细表##期初余额##免征增值税项目销售额-->
			<ckmszzsjmssbmxbqcyemzzzsxmxse/>
		</jmsmxbGridlbVO>
		<!--2##跨境服务-->
		<jmsmxbGridlbVO>
			<ewbhxh>4</ewbhxh>
			<!--免税项目##跨境服务##增值税减免税申报明细表##期初余额##免征增值税项目销售额-->
			<kjfwzzsjmssbmxbqcyemzzzsxmxse/>
		</jmsmxbGridlbVO>
		<!--1-->
		<jmsmxbGridlbVO>
			<ewbhxh>5</ewbhxh>
			<!--免税项目##增值税减免税申报明细表##本期发生额##免税销售额扣除项目本期实际扣除金额-->
			<zzsjmssbmxbbqfsemsxsekcxmbqsjkcje/>
			<!--免税项目##增值税减免税申报明细表##减税性质代码及名称##1-->
			<zzsjmssbmxbjsxzdmjmc1/>
			<!--免税项目##增值税减免税申报明细表##本期应抵减税额##扣除后免税销售额-->
			<zzsjmssbmxbbqydjsekchmsxse/>
			<!--免税项目##增值税减免税申报明细表##本期实际抵减税额##免税销售额对应的进项税额-->
			<zzsjmssbmxbbqsjdjsemsxsedydjxse/>
			<!--免税项目##增值税减免税申报明细表##期末余额##免税额-->
			<zzsjmssbmxbqmyemse/>
			<!--免税项目##增值税减免税申报明细表##期初余额##免征增值税项目销售额-->
			<zzsjmssbmxbqcyemzzzsxmxse/>
		</jmsmxbGridlbVO>
		<!--2-->
		<jmsmxbGridlbVO>
			<ewbhxh>6</ewbhxh>
			<floatrow>1</floatrow> <!-- 免税项目 如果要是 还有数据 以此类推  floatrow 值为 2 、3 、4 等等-->
			<!--免税项目##增值税减免税申报明细表##期末余额##免税额-->
			<zzsjmssbmxbqmyemse/>
			<!--免税项目##增值税减免税申报明细表##减税性质代码及名称##1-->
			<zzsjmssbmxbjsxzdmjmc1/>
			<!--免税项目##增值税减免税申报明细表##本期实际抵减税额##免税销售额对应的进项税额-->
			<zzsjmssbmxbbqsjdjsemsxsedydjxse/>
			<!--免税项目##增值税减免税申报明细表##本期发生额##免税销售额扣除项目本期实际扣除金额-->
			<zzsjmssbmxbbqfsemsxsekcxmbqsjkcje/>
			<!--免税项目##增值税减免税申报明细表##本期应抵减税额##扣除后免税销售额-->
			<zzsjmssbmxbbqydjsekchmsxse/>
			<!--免税项目##增值税减免税申报明细表##期初余额##免征增值税项目销售额-->
			<zzsjmssbmxbqcyemzzzsxmxse/>
		</jmsmxbGridlbVO>
	</jsxgs_zzs_ybnsr_jmsmxb>
	<!-- 新国税增值税一般纳税人申报表 附表五 -->
	<jsxgs_zzs_ybnsr_fb5/>
	<!-- 新国税增值税一般纳税人申报表 应税服务减除项目清单 -->
	<jsxgs_zzs_ybnsr_jcxmqd>
		<!--2_floating_r5_-->
		<jcxmqdGridlbVO>
			<ewbhxh>1</ewbhxh>
			<floatrow>1</floatrow>
			<!--2_floating_r5_##金额-->
			<je/>
			<!--2_floating_r5_##开票方单位名称-->
			<kpfdwmc/>
			<!--2_floating_r5_##开票方纳税人识别号-->
			<kpfnsrsbh/>
			<!--2_floating_r5_##凭证种类-->
			<pzzl/>
			<!--2_floating_r5_##发票号码-->
			<fphm/>
			<!--2_floating_r5_##发票代码-->
			<fpdm/>
			<!--2_floating_r5_##服务项目名称-->
			<fwxmmc/>
		</jcxmqdGridlbVO>
	</jsxgs_zzs_ybnsr_jcxmqd>
	<!-- 新国税增值税一般纳税人申报表 [015]生产企业进料加工抵扣明细表 -->
	<jsxgs_zzs_ybnsr_scqy15/>
	<!-- 新国税增值税一般纳税人申报表 [016]生产企业出口货物征（免）税明细主表 -->
	<jsxgs_zzs_ybnsr_scqy16/>
	<!-- 新国税增值税一般纳税人申报表 [017]生产企业出口货物征（免）税明细从表 -->
	<jsxgs_zzs_ybnsr_scqy17/>
	<!-- 新国税增值税一般纳税人申报表 [018]国际运输征免税明细数据 -->
	<jsxgs_zzs_ybnsr_scqy18/>
	<!-- 新国税增值税一般纳税人申报表 [019]研发、设计服务征免税明细数据 -->
	<jsxgs_zzs_ybnsr_scqy19/>
	<!-- 北京地区使用 必填，其他扣税凭证明细表 都必须为大于等于0  ##新增 江苏不需要传##-->
	<jsxgs_zzs_ybnsr_qtkspzmxb>
	  <qtkspzmxGridlbVO>
	     <ewbhxh>1</ewbhxh>
		 <!-- 有效标志 -->
		 <yxbz/>
		 <!-- 桥、闸通行费份数 -->
		 <txffs/>
		 <!-- 桥、闸通行费金额 -->
		 <txfje/>
		 <!-- 桥、闸通行费税额 注：必须小于等于10000元 -->
		 <txfse/>
		 <!-- 国内旅客运输服务份数 -->
		 <ysfwfs/>
		 <!-- 国内旅客运输服务金额 -->
		 <ysfwje/>
		 <!-- 国内旅客运输服务税额 -->
		 <ysfwse/>
		 <!-- 不动产转变用途可以抵扣的进项税额份数 -->
		 <jxsefs/>
		 <!-- 不动产转变用途可以抵扣的进项税额金额 -->
		 <jxseje/>
		 <!-- 不动产转变用途可以抵扣的进项税额税额 -->
		 <jxsese/>
	  </qtkspzmxGridlbVO>
	</jsxgs_zzs_ybnsr_qtkspzmxb>
</jsxgs_zzs_ybnsrxxVO>
'''
# print(json.dumps(xml_to_dict(xml),indent=4))
xml_dict = xml_to_dict(xml)
# {'jsxgs_zzs_ybnsrxxVO':{'sbbinfo':{'sbzlbh':'10101',...},'jsxgs_zzs_ybnsr_sbb':{'sbbGridlbVO':[{'ewbhxh':'1',...},...]},'jsxgs_zzs_ybnsr_scqy15':None,...}}
# print(list(xml_dict.keys())[0]) #   xml_dict.keys():dict_keys(['jsxgs_zzs_ybnsrxxVO'])
xml_name = list(xml_dict.keys())[0]  # jsxgs_zzs_ybnsrxxVO
forms_name = list(list(xml_dict.values())[0].keys()) # ['sbbinfo', 'jsxgs_zzs_ybnsr_sbb',...]
# xml 创建xml
xml_id = shenbaosheet.create({'name': '增值税一般纳税人-江苏',  'description': '增值税一般纳税人-江苏', 'dqbm': '32', 'tagname': xml_name})
# forms
for form_name in forms_name: # ['sbbinfo', 'jsxgs_zzs_ybnsr_sbb',...]
    # 创建表
    form_id = shenbaosheet.create({'parent_id': xml_id, 'name': form_name, 'description': form_name, 'dqbm': '32', 'tagname': form_name})
    # 非空表 有两种情况    1.字典的value是列表     2.字典
    if xml_dict[xml_name][form_name]:
        # xml--form--line--cell   1.字典的value是列表  {'sbbGridlbVO':[{'ewbhxh':'1',...},...]}
        if isinstance(list(xml_dict[xml_name][form_name].values())[0],list):
            # 创建行
            line_name = list(xml_dict[xml_name][form_name].keys())[0]
            line_id = shenbaosheet.create({'parent_id': form_id, 'name': line_name, 'description': line_name, 'dqbm': '32',
                                 'tagname': line_name})
            # 创建单元格 [{'ewbhxh':'1',...},...]
            for cell_dict in xml_dict[xml_name][form_name][line_name]:
                cell_line_num = int(cell_dict['ewbhxh'])
                cell_name_list = list(cell_dict.keys())
                # ['ewbhxh', 'yybjsffjsqbz', 'yybjs']
                for cell_name in cell_name_list:
                    if cell_name != 'ewbhxh':
                        shenbaosheetcell.create({'sheet_id': form_id, 'line': cell_line_num, 'tagname': cell_name})
        # xml--form--cell   2.字典 ps:直接else就可以，只是让逻辑更清晰   {'sbzlbh':'10101',...}
        if isinstance(xml_dict[xml_name][form_name],dict):
            # 创建单元格
            cell_name_list = list(xml_dict[xml_name][form_name].keys())
            for cell_name in cell_name_list:
                shenbaosheetcell.create({'sheet_id': form_id, 'tagname': cell_name})
    # # 空表 只需要创建表对象即可
    # else:
    #     pass



